### ISSUE TITLE
Quadplane motors spin up when connecting power

### ISSUE THREAD

**Issue by blyterate** [ArduPilot/ardupilot#10068]
Aircraft VTOL Motors power on when connecting battery. 

Arduplane 3.9.3

Quadplane airframe type 
#### Version

3.9.3

#### Platform
[  ] Plane

#### Airframe type
 Octo Quadplane 

#### Hardware type

Pixhawk 2.1 Cube, Here+ GPS, Castle Creations DMR 30/40 ESC 

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by Naterater** [comment]
We really need logs to re-create your issue. Have you calibrated your ESC's recently? Does the motor RPM change during boot? Is it idle speed or full speed? How long does it last?

**Comment by lowlyelevated** [comment]
I've seen an issue where all of my servos (connected to the cube 2.1 main out) move on boot. I actually killed two quadplane tilt servos this week because of it. Unfortunately, the logs aren't very helpful, because the behavior begins before logging even initializes. 
I've never had motors spin up, but my motors are connected to the aux out ports on the cube 2.1. So maybe it only affects the main out ports? Or maybe your ESCs are responding the the erroneous input differently than mine are. (I'm using flyfun 40a units) 

I'm just spitballing here, I've honestly got no clue what's causing it. this old Discuss thread may be of interest? https://discuss.ardupilot.org/t/servos-at-extreme-positions-during-boot/20296/30

**Comment by WickedShell** [comment]
Was this ChibiOS or PX4 based builds? I've seen this under PX4 builds, and the root problem there is fixed under the ChibiOS ones.

**Comment by IamPete1** [comment]
@WickedShell says this is fixed on ChibiOS
