### ISSUE TITLE
AP_RangeFinderParams: RNGFND not collapsed if NONE

### ISSUE THREAD

**Issue by olliw42** [ArduPilot/ardupilot#10502]
@256shadesofgrey , @rmackay9 
in this line
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_RangeFinder/AP_RangeFinder_Params.cpp#L13
you probably want(ed) to use
`AP_GROUPINFO_FLAGS("TYPE",    1, AP_RangeFinder_Params, type, 0, AP_PARAM_FLAG_ENABLE),`
instead

(the 0 should be replaced with RangeFinder_TYPE_NONE, this would in addition requires moving the RangeFinder_Type enum to AP_RangeFinderParams.h, see e.g. BATT_MONITOR)

**Comment by olliw42** [comment]
and to be consistent with COMPASS, BATT_MONITOR, BARO, GPS, ... one probably wants to rename RNGFND1_XXX to RNGFND_XXX

**Comment by rmackay9** [comment]
I also noticed the issue with the first rangefinder being called RNGFND**1**_ instead of just RNGFND_

**Comment by olliw42** [comment]
I probably should have added this
just delete the 1 in the strings here https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_RangeFinder/RangeFinder.cpp#L49 and here https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_RangeFinder/RangeFinder.cpp#L53
:)

**Comment by rmackay9** [comment]
.. and there's probably a small change that needs to be made to the parameter conversion handling code as well..

**Comment by olliw42** [comment]
to continue with improvement, note that these parameters

pin
ratiometric
powersave_range
stop_pin
settle_time_ms
scaling
offset
function

are used by ONLY AP_RangeFinder_analog.cpp and/or AP_RangeFinder_PX4_PWM.h. That is these should be moved to the backend, like it's done for the WASP rangefinder. Since these are 8 params, and there are 10 rangefinders, this would reduce the number of parameters MP and the user has to deal with by a staggering 80 !!! (which is probably nearly 10%). This would make it really much more practical to use 10 rangefinders.
IMHO.

(I've done that for my betacopter fork, and it really looks so much better, from a user perspective ;))

**Comment by khancyr** [comment]
agree ! 80 less useless parameter is a big deal !

**Comment by 256shadesofgrey** [comment]
@olliw42 Copy pasta from my PR in regards to moving parameters to backend, since this was one of the first things that were considered:

The problem with adding parameters like `_ADDR` to the backend is that with the current implementation many backends require an instance of `AP_HAL::OwnPtr<AP_HAL::I2CDevice>` to be passed, which in turn requires an address which we don't have until we call `detect()`. To move parameters to the backends we would have to change the design of at least 5 already existing drivers, moving the `hal.i2c_mgr->get_device()` calls inside the drivers and making the `detect()` functions less "intelligent" (and at this point I'm starting to question why we need `detect()` at all).

So yeah, it would make it cleaner, but it's quite a bit of work for just aesthetics.

**Comment by olliw42** [comment]
_ADDR was not in my list of params I suggested to move ;)

**Comment by IamPete1** [comment]
closed by https://github.com/ArduPilot/ardupilot/pull/14560
