### ISSUE TITLE
Copter: what happened to LED_mode?

### ISSUE THREAD

**Issue by NullVoxPopuli** [ArduPilot/ardupilot#1082]
see: http://diydrones.com/forum/topics/ac-3-1-1-led-mode-is-missing?commentId=705844%3AComment%3A1638731&xg_source=activity  
and: http://diydrones.com/profiles/blogs/adding-external-led-indicators-and-a-piezo-beeper-for-arm-and-gps

Just checking through the Full Parameter List and also searched through all the code in the most recent code from master as of the time of the creation of this issue. 

Are there plans to bring it back? Is there an alternative way to configure External LEDs?

**Comment by UT99310** [comment]
This thread probably isn't quite on-topic but it seems pretty close, so we'll give it a try. I already have ARM and GPS LEDs set up externally that work with my existing APM 2.5. I'd prefer to keep them as they are when I upgrade to a Pixhawk. I can see that there are various i2c-based LED solutions but if possible I'd really like to simply connect my existing LEDs to Pixhawk AUX OUT outputs rather than set up a new LED board. Is there a practical way to do this, so that my ARM and GPS LEDs will work the same on the Pixhawk as they do on APM? Thanks!

**Comment by rmackay9** [comment]
@UT99310, I'm afraid we don't support the APM2 style LEDs on the Pixhawk.  It's not technically super difficult to do it's just that nobody's done the software for it.
Personally I prefer the Pixhawk LEDs but I can imagine that it takes an adjustment and who knows, that may also just be me.

**Comment by UT99310** [comment]
Understood. Thanks.
