### ISSUE TITLE
Copter: AC3.2 - ensure auto mode is in valid state if first nav command is invalid

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#1126]
In the case where the first navigation command in the mission is a command that is not accepted by arducopter, it may leave the auto_mode in an invalid state.

**Comment by nitirohilla** [comment]
@rmackay9 . Could you please confirm is this bug still open ?? 

As I am not able to reproduce it at my end. Could you please suggest a scenario to replicate this issue at my side so that I can pick it up.

**Comment by rmackay9** [comment]
@nitirohilla, sorry I didn't see your question.  A lot of time has passed but in any case, I think the only way to reproduce this issue is to make the mission start with a navigation command that Copter doesn't support.  I can't immediately think of one that would work but perhaps command 30 (	MAV_CMD_NAV_CONTINUE_AND_CHANGE_ALT).  That's certainly not supported by ardupilot so I wonder what will happen to Copter if that's the first mission item in the list.  Maybe nothing will happen in which case we can close this issue.

**Comment by rmackay9** [comment]
I think I'll push this to AC3.5 in any case.

**Comment by OXINARF** [comment]
After analyzing code and doing a SITL test I concluded this isn't a problem.

Code analysis:

- it isn't possible to save unrecognized commands, but a command can be used in one vehicle and not in another, so it is possible to save a command that Copter doesn't recognize but other vehicles do
- arming in Auto isn't possible
- if already armed but on the ground, first command has to be a takeoff
- if already in the air, when entering Auto, *auto_mode* is placed into Auto_Loiter
- mission starts running and as with every command that is loaded, the *start_command* method is called and [unrecognized commands simply don't do anything](https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/commands_logic.cpp#L163-L165)
- given that *auto_mode* stays in Auto_Loiter, copter will just loiter
- AP_Mission _update_ method is called periodically and from there Copter's *verify_command* is called to see if current command was completed; since [command is unrecognized a message is sent to GCS and the command deemed as terminated](https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/commands_logic.cpp#L274-L279)
- next command loaded as normal and *auto_mode* will change accordingly

SITL testing:

- the suggested command (MAV_CMD_NAV_CONTINUE_AND_CHANGE_ALT) is supported by Plane, but not Copter so perfect to test this; after some tests everything behaved as expected
- I also wanted to test a command that no vehicle supported so I simply added MAV_CMD_NAV_FOLLOW case (with a simple _break_ statement) to AP_Mission [when receiving the mission item](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Mission/AP_Mission.cpp#L781) and [when sending it back](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Mission/AP_Mission.cpp#L1231); this allowed to save the command to EEPROM and when running a mission once again everything went as expected, with the unrecognized command being skipped.

One thing I didn't test was putting the unrecognized command in the middle of the mission, but, given the code analysis, I'm 99.9% sure nothing bad will happen, command will just be ignored.
