### ISSUE TITLE
Copter: optical flow does not work on FLOW_TYPE=5(Mavlink, openmv) 

### ISSUE THREAD

**Issue by MrThanlon** [ArduPilot/ardupilot#11323]
Questions and user problems should be directed at the forum (http://discuss.ardupilot.org)
_**Please be very sure you have found a bug when opening this issue**_
If there was a previous discussion in the forum, link to it

### Bug report

**Issue details**

_Please describe the problem_

**Version**
_What version was the issue encountered with_

**Platform**
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

**Hardware type**
_What autopilot hardware was used? (Pixhawk, Cube, Pixracer, Navio2, etc)_
Pixhawk & PXFmini
**Logs**
_Please provide a link to any relevant logs that show the issue_
```
Bad OptFlow Health
```

**Comment by rmackay9** [comment]
I'm afraid OpenMV support hasn't been released officially yet (on our [OpenMV wiki page](http://ardupilot.org/copter/docs/common-openmv-optflow.html) we have the note, "Support for this sensor will be included in Copter-3.7 (and higher)").

Until 3.7.0 has been released, support is only available in "latest" which can be loaded using the Mission Planner's Install Firmware screen after pressing Ctrl-Q.  Normally we don't recommend running "latest" though because it is untested.  A much better choice would be to wait for Copter-3.7.0-rc1 (the first beta) which will begin testing in a couple of months.

I think I'll close this issue if that's OK.  Thanks for using AP!
