### ISSUE TITLE
Copter: AC3.2 - check 2nd accel in pre-arm checks

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#1142]
In AC3.2 we rely on the backup accelerometers (on the px4/pixhawk) but we don't during the pre-arm checks that they've been calibrated.  This can mean that AC3.1 users who haven't done their accel calibration since we added support in the code and misssion planner have zero accel scaling and offsets.
This leads to very incorrect inertial nav alt and position estimates.

**Comment by pcace** [comment]
@churl11 did you read this? http://diydrones.com/forum/topics/pixhawk-bad-accel-health-apm-3-2-collecting-data?id=705844%3ATopic%3A1853847&page=34#comments

**Comment by magicrub** [comment]
I believe this has been fixed in master, a new release is needed.

**Comment by pcace** [comment]
nope i dont think so. i am using the latest dev build, and without disabling prearm checks, i am not able to arm the copter in most situations (getting bad accel health)

Greetings

**Comment by magicrub** [comment]
Ahh, you may be right. There have recently been several fixes in this area
but perhaps they were only applied to Plane and haven't been ported to
copter yet.

Randy and Tridge, can you follow up on this thread please as I'm not a
copter guy?

**Comment by pcace** [comment]
Yes, if there would be a fix soon it would be just awesome! 
Right now i am thinking to swich back to APM 2.6, because i just cannot trust the Pixhawk (clone) i am using right now.. When looking into the logs the only strange thing is, that sometimes (when i cannot arm) the second imu just gets 0 data... 
Is there anything i can do right now to kind of fix this? Or to completely disable the second imu? (which i think is the troublemaker?
Example logs can be seen here: http://johannes-froelich.de/daten/temp/logs/logs.zip
Greetings,
Pcace

**Comment by magicrub** [comment]
Setting AHRS_EKF_USE=0 makes the behavior the same as your APM 2.6.

**Comment by magicrub** [comment]
If you are having problems in master using pixhawk with EKF enabled, please
submit a log to help us out.

**Comment by pcace** [comment]
Yes, i uploaded them here: 
http://johannes-froelich.de/daten/temp/logs/logs.zip
If this is not the right place to post the logs, please direct me to a better place!
There are 3 Logs inside. 
- one is when trying autotune (the result was nearly unflyable and almost crashed - second imu was not recognized or it just showed values 0
- one is where both imus were recognized
- and the last one was a strange fly, because the Pixhawk thought that i landed 8m above the "home" position (thats why i was flying in stabilize - i was too scared to try auto flight...)

Thank you so much for your awesome work!!!

**Comment by magicrub** [comment]
Thanks for the logs!
