### ISSUE TITLE
ChibiOS: intermittent no-link messages on mavproxy

### ISSUE THREAD

**Issue by arjun7965** [ArduPilot/ardupilot#11619]
### Bug report

**Issue details**
We have a pixhawk cube (3.6.9/master branch) connected to a Raspberry pi compute model via USB. Mavproxy on the Rpi intermittently display "no link" messages. During this nothing can be read from the pixhawk like "battery_status" or "SYS_STATUS" for example but, a reboot command goes through and reboots the pixhawk.  

It appeared that MAVProxy wasn't seeing any messages from the autopilot--none of the counters were updating AFAICT: "wp list" didn't work; "param fetch" didn't work

mavproxy did respond to commands, and showed that it was sending them to the autopilot,
just didn't seem to be getting responses.

Running stty on the serial device (just opening + querying it) didn't work. Well, it worked in that it's able to open the device and retrieve the serial parameters, but it didn't have any effect on the link status in mavproxy. Using stty to toggle the baud rate back and forth likewise.

Trying a restart of mavproxy... Link still down

"cat /dev/serial/by-id/usb-ArduPilot_fmuv3_23001D000B51383130383938-if00" seems to just return immediately.

Looks like read() on the FD is just returning zero, which is EOF as far as cat is concerned.

Has anyone else had this issue? I have never seen this while using NuttX. 

Any help is appreciated

**Version**
Copter-3.6.9 and master branch 

**Platform**
[ x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
_N/A_

**Hardware type**
_Cube_

**Comment by OXINARF** [comment]
This issues list is for feature requests and confirmed bugs. For user support please post in the forum (http://discuss.ardupilot.org).

**Comment by rozzin** [comment]
The subject should be something more like "MAVLink output on Cube USB-serial link unexpectedly stops, produces only EOF when reading from USB host".

It looks like a bug to me.

I know the way @arjun7965 wrote the subject, it sounded like it could just be a MAVProxy usage issue; but "no output at all, just EOF" on the USB-serial interface as seen by the host computer is clearly something else.

It really looks like the the link on the autopilot somehow becomes one-way-only (packets go in, they don't come out). If this was actually a serial link instead of the USB link, I could see how messing up the flow-control settings could cause something like this..., but I don't think there even are flow-control settings for the USB serial emulation, are there?

**Comment by OXINARF** [comment]
> The subject should be something more like "MAVLink output on Cube USB-serial link unexpectedly stops, produces only EOF when reading from USB host".
>
> It looks like a bug to me.

@rozzin No, it looks like an issue. There is no evidence of a bug and it certainly isn't a **confirmed** bug.

I'm sorry but if we allow support here, the list would be at 10000 open issues instead of the (already unmanageable) 1200.
