### ISSUE TITLE
Copter Terrain avoidance  following

### ISSUE THREAD

**Issue by roque-canales** [ArduPilot/ardupilot#11620]
Hello today copter is able to follow terrain through terrain data.

There is possible to create our own terrain data? With more details than srtm? Maybe using qgis?

Does anybody could help me to do that?

**Comment by rmackay9** [comment]
@roque-canales, it is at least theoretically possible but it's actually a ground station issue (i.e. Mission Planner) more than a flight code issue.  The way it works is the vehicle code requests the terrain altitude from the GCS which then provides it.

I've heard that MP does support a way for custom terrain data to be used but I'm not sure exactly how that works.

I think I'll close this because it's less of a vehicle code issue than a GCS issue.
