### ISSUE TITLE
Copter v3.1.5 Pixhawk dataflashlogs using log date from 1970

### ISSUE THREAD

**Issue by matsta** [ArduPilot/ardupilot#1171]
On Pixhawk with firmware 3.1.5 the log files are named not with the actual date for creation but using same date starting from Thu Jan 1 1970 T 01:00:00 something.

The id is counted up correct but the time is wrong making the log feature unusable.

See this image for more info:
http://postimg.org/image/awxxt6qu7/  

Should add that I'm on a linux(ubuntu) system while d/l logs.

**Comment by WickedShell** [comment]
Since the clock wouldn't keep time between boots you would end up having a log that has an identical start time to the end of the last log, which would be far more confusing. (IE say I last flew on the 10th at  4 pm and its now the 14th and I log I would have a log stating the 10th at 4pm). I would say the 1970 date behavior in the case of no time source is probably better and that this could be closed. Thoughts?

**Comment by peterbarker** [comment]
@WickedShell Agreed.

Modern tools do well with this.
