### ISSUE TITLE
Hereflow integration issues with Pixracer

### ISSUE THREAD

**Issue by myeabhishek** [ArduPilot/ardupilot#12011]
I am using hereflow camera with pixhawk 2 hardware. I want to move to pixracer, however, I can't get the driver to work.

Is the Hereflow camera even compatible with Pixracer? If not what do I need to do to add the support?

**Comment by rmackay9** [comment]
@myeabhishek, thanks for using AP.

I guess you've seen the [HereFlow stup wiki page](http://ardupilot.org/copter/docs/common-hereflow.html).  One key thing to note is that the driver is not included in the current stable release.  Copter-3.7 should begin beta testing in a few weeks we just have a few final developments to finish off.

By the way [support issues should normally be raised in the forums](https://discuss.ardupilot.org/c/arducopter/copter-36) instead of here.
