### ISSUE TITLE
Simulator Segfault with Spline WP

### ISSUE THREAD

**Issue by tilaktilak** [ArduPilot/ardupilot#12215]
## Bug report

**Issue details**

I observe a repeatable segfault sending WP as Splines

**Version**
Master branch, d774bf3ea51700977e99e565c6a3b64533e6c4f7

**Platform**
[  ] All
[  ] AntennaTracker
[ X ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Simulator

**Logs**

![screenshot](https://user-images.githubusercontent.com/6662416/64307914-a3918d00-cfeb-11e9-8f92-7820de8bae5b.png)

Here logs bin and telemetry logs from both Simulator and QGC.  
[segfault_ardupilot.zip](https://github.com/ArduPilot/ardupilot/files/3577232/segfault_ardupilot.zip)

Here a flight plan that reproduce the issue (Export from QGC, need to remove .log extension) : 
[test.plan.log](https://github.com/ArduPilot/ardupilot/files/3577252/test.plan.log)

**Comment by WickedShell** [comment]
This isn't actually a segfault, it's a panic. I'm not sure why panic in SITL look like segfaults these days, but there you go.

Anyways the root problem is that a call for `get_alt_cm()` has been made on a location that was not initialized (which was defined as lat/long both being 0). This will currently happen whenever a spline waypoint is the last thing in the mission. Briefly looking at the code in the spline controller I think it's actually safe. It's precalculating a vector I don't believe it uses if its the last spline waypoint. @peterbarker I'm chucking this at you as your problem since you introduced the check :)
