### ISSUE TITLE
PPM encoder adds lag to input

### ISSUE THREAD

**Issue by lion13ch** [ArduPilot/ardupilot#1238]
Pixhawk (with 3Dr PPM Encoder or Frsky PPM signal) have PPM input lag (delay). 
Lag (delay) is between rc roll/pitch stick is moved and copter begin to roll/pitch. 
Lag was found at AC3.2rc3 as well AC3.2rc2 and AC3.1.5. Lag is about 50-70 msec.
There is no lag with S.Bus input and no lag at APM2.5 with PWM and PPM input.
Can It be fixed ?

**Comment by rmackay9** [comment]
We're out of time for AC3.3 so pushing to AC3.4.

**Comment by WickedShell** [comment]
Somewhere between plane 3.2 and 3.3 this got far better for plane, I'd be interested if it's still a problem on copter. I did testing with plane 3.3 and an oscilloscope and in manual was getting the correct servo outputs requested as soon as was possible. (Startup could introduce a time offset between the RC reciever, ppm encoder, and pixhawk which can affect the worst case pass through time, but the pixhawk was doing as good as it possibly could be expected to).

**Comment by rmackay9** [comment]
Not sure if this is still a problem or not but pushing to AC-3.5 in any case.

**Comment by hiro2233** [comment]
@rmackay9 i have investigated this problem, i had the same problem when i use the ppm, it's happening because the time interrupts are individual for each channel in serial transmision with an unkwon time interrupt intervals between the channels and it take little microseconds difference, but it has a big impact when the copter autoactivate the auto trim after the 20 seconds in the loop, i deactivate this by hardcoded an the problem go out but without auto trim.

The reason that it work fine in a SBUS are because the data adquisicion process do it when it fill the buffer and then finish the process it to complete data channel and fire it.

**Comment by Naterater** [comment]
Still relevant with ChibiOS?

**Comment by rmackay9** [comment]
I don't think hardly anyone uses PPM encoders any more.  It was really transitional while the old individual channel RC receivers were still popular.  I'll close this I think.
