### ISSUE TITLE
 Quadrocuper with gasoline engine

### ISSUE THREAD

**Issue by okotik** [ArduPilot/ardupilot#12551]
Hello. I want made quadrocuper with gasoline engine. I will use servo drives to control the acceleration. Can I use the same firmware used for electric motors?

**Comment by rmackay9** [comment]
This is really a support question so it should be raised in the support forums here: https://discuss.ardupilot.org/c/arducopter/copter-36.  Sorry to be strict but otherwise our developer to-do list turns into (another) support forum.

The short answer is yes and we have some info on the wiki here: http://ardupilot.org/copter/docs/common-ice.html.
