### ISSUE TITLE
Copter: package place gets stuck if lat,lon are defined

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#12570]
Based on the discussion here it seems that Copter's Package Place mission command gets stuck if the user defines the lat and lon.  A work around is to use a waypoint command to get to the desired location and then use a package-place command with no lat,lon defined but we should still fix the underlying problem.

**Comment by nkruzan** [comment]
Looks like maybe this just need to have cmd.content.location.lat = packet.param5 and cmd.content.location.lng = packet.param6 set here https://github.com/ArduPilot/ardupilot/blob/c1c329e2b4f2750deae14d14c95ee87aebd2248b/libraries/AP_Mission/AP_Mission.cpp#L1135

does that seem right? I'll work on a pr if i'm on right track.

**Comment by rmackay9** [comment]
@nkruzan

That sound like it could be the issue, txs!

**Comment by lthall** [comment]
Could you please check this again using #21296.

Thanks for catching this!!

**Comment by peterbarker** [comment]
I am unable to replicate here.  The vehicle drops the payload at the specified coordinates (augmented test here: https://github.com/ArduPilot/ardupilot/pull/21298/files)

There's no link to the original discussion.  Leonard *has* fixed issues where it might get stuck in his PR if the vehicle didn't have a gripper configured (IIRC).

Since there's no link to further information, I think we have to assume it's either been fixed already, or that the original vehicle didn't have a gripper enabled (in which case it wouldn't have worked without lat/lng supplied either.

The code line referenced isn't relevant - the message is marked as "stored in location", meaning we fill lat/lng/alt in a different part of the code.

Please reopen this if more information is/becomes available.
