### ISSUE TITLE
Copter: altitude drop after fast foward flight (aerodynamic effect upsets baro)

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#1277]
There is a well documented aerodynamic effect that causes the barometer altitude to suddenly climb when a multicopter flattens out after fast forward flight (actually it can be sideways as well).

https://www.youtube.com/watch?v=Vn-Fg53Or4c#t=124

The effect can be reduced slightly by increasing the INAV_TC_Z time constant from 5 (it's default) to 7 but there may be other solutions including:
1. software algorithm to account for the expected increase in pressure based upon the vehicle attitude and velocity.
2. hardware solution by mounting the barometer on a pole within a round ball with holes in it that provides equal pressure regardless of vehicle velocity.

**Comment by rmackay9** [comment]
It doesn't seem to me we have much hope of fixing this problem in software but pushing to AC3.4 anyway.

**Comment by umfundi** [comment]
( Finally something I think I know a little about! ) Not an easy fix in software as it is directly related to how and where the barometric sensor gets its 'static' reference from. In flying full sized sailplanes a compensated variometer or total energy vario is crucial to detecting whether the air around you is truly rising or sinking or whether you are experiencing 'stick lift' ie converting energy to height or visa versa. Although we are not interested in a climb/sink reading we are interested in total altitude and the effects are the same.

Generally in a mechanical system a bleed capilliary tube is taken from the airspeed input to the variometer which is measuring the flow in to and out of a capacity. ( flask ) you get secondary effects due to the heating of air expanding and contracting too. Modern variometers use solid state barometric sensors in much the same way we are using them on our systems but they also sense airspeed to arithmetically compensate for total energy. Some modern sailplane systems also detect G to compensate for zoom and pushover when flying.

All fine and well in a fixed wing aircraft that has a sharp end and generally don't go sideways and do have airspeed sensors!

What is happening in the video appears to be the airflow around the airframe is causing a slight decrease in pressure ( as  per Bernoulli ) the flight algortihm is maintaining a steady altitude based mostly on INS but when the vehicle comes to a halt it is seeing a sudden low pressure spike and compensates for what it believes is a small climb so it drops the vehicle.

So 

Trying to compensate out as a general solution may not work satisfactorily for everyone, some airframes will be better than others at presenting a good static reference to the baro sensor..

Sensing ground speed from the GPS is not enough as there could be significant effects layered from wind effects, some idea of wind speed and direction is required to reflect a true airspeed.

To fix this it may be necessary to either ....
implement wind speed and direction calculations and plot the effect on the baro sensor ( not too difficult given we have solid GPS and inertial nav ) and plotting a correction curve.

Implement a calibration process ( part of  autotune? ) that tests the effects of various flight speeds on baro sensor. Fly the aircraft forward, backward, left, right and perhaps diagonally and in a basic aircraft get the pilot to input an estimated height loss on stopping. With Lidar or similar it is of course far simpler to build up the compensation table! :)

**Comment by umfundi** [comment]
Does anyone have some log files from testing this effect? Would be interesting to see what the real sensor values are.

**Comment by amdeus** [comment]
3.3.1  x8 multirotor with 4kg. pixhawk. Logs:
https://www.dropbox.com/sh/nnchx7devxflvt9/AACxiNcWreJlFBsck_lhnbBia?dl=0

autotune flight. ever time i take my copter back (fast fligth in alt hold mode) i have to open trottel the whole way. if not the copter would have hit the soil.


![20151116_174708](https://cloud.githubusercontent.com/assets/15889119/11210835/340a359c-8d2b-11e5-94f4-f49b1139f61c.jpg)

**Comment by k5beason** [comment]
I've attached my log. You can see anytime ground speed is increased from 0 the Barometer reports a climb and thus the copter descends. 

https://www.dropbox.com/s/2sll9w1ly3jnfrv/2015-12-02%2017-35-49.tlog.zip?dl=0

**Comment by rmackay9** [comment]
Here's the diydrones discussion on this topic as well: http://diydrones.com/forum/topics/effects-of-frame-design-on-barometer-performance-and-all-other

**Comment by govsux** [comment]
re-" Implement a calibration process ( part of autotune? ) that tests the effects of various flight speeds on baro sensor. "
Altitude can be seen by the gps too right? Perhaps a new autotune as suggested by using the gps with 10 sats or more then you fly around at high speeds and it sees what effect the baro is seeing with different speed and directions compared to the gps and so then it can be calibrated with that info to zero out the effect??

**Comment by rmackay9** [comment]
We're not going to get to this in AC3.4 so bumping to AC3.5.

**Comment by shazzy1** [comment]
Has the INAV_TC_Z term been removed from v3.3.2? Not seeing it anywhere on MP v.1.3.39.

Cheers

**Comment by geofrancis** [comment]
i have done a fair amount of testing with this and it only occours when the pixhawk is mounted on top of the machine directly in the path of oncoming air. just by putting a small dome over it to shield it got rid of all the baro problems.

same issue on a pixhawk mounted between the plates on a s900, it would loose altitude at speed and by just taping up the holes on the top plate pixhawk was shielded and the problems went away. 

so rather than this being a software problem its more of a aerodynamic problem that can be solved easily by better placement or shielding of the flight controller.

**Comment by govsux** [comment]
@ geofrancis  I agree. Just an added note there thus far seems no great solution to having a water-proof drone. I tried many different ideas and gave up as the baro, as sensitive as it is, could not deal with any of the rudimentary mechanical solutions. Once exposed to water airflow was impaired. Drastic unexpected changes in altitude resulted. I'm certain a creative solution can be found but I didn't find it and it still seems like it would be a mechanical one.

**Comment by auturgy** [comment]
suggest closed by https://github.com/ArduPilot/ardupilot/pull/15774

**Comment by rmackay9** [comment]
yes, I think we can close this now that we have wind estimation in 4.1.  I haven't actually tested that it works but let's assume that it does.

**Comment by DavudSuleymanov** [comment]
We are having this problem on X8 quadcopter and although we tried many things, we could not find a software solution. This so called value has now been removed. What can be done from ardupilot software?

**Comment by rmackay9** [comment]
@DavudSuleymanov,

It is best to try and solve the solution in hardware but if that is not possible then setting up [wind estimation and baro compensation could help](https://ardupilot.org/copter/docs/airspeed-estimation.html).
