### ISSUE TITLE
Battery percentage toggles multiple times from 0 to 100

### ISSUE THREAD

**Issue by Vishranthee** [ArduPilot/ardupilot#13037]
Current battery voltage is 11.66 but the battery percentage switches from 0 to 100 like a flicker.

Arducopter 3.6.11

#### Platform
[  ] All
[  ] AntennaTracker
[X ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
Quad ( similar to F450)

#### Hardware type
Pixhawk

#### Logs
_Please provide a link to any relevant logs that show the issue_
![battery percentage](https://user-images.githubusercontent.com/32018358/70610245-40864680-1c29-11ea-9bbb-430afff87ae0.png)

**Comment by rmackay9** [comment]
This is really a support issue so it should go into [the forums](https://discuss.ardupilot.org/c/arducopter/copter-36).  Sorry to be strict but otherwise our to-do list turns into a support forum.

If you open an issue in the forums, please post a reply here with a link.  Also providing a log file would be good.  A dataflash log and if possible a tlog... but whatever you have
