### ISSUE TITLE
FrSky Telemetry on Kakute F7 not working as described

### ISSUE THREAD

**Issue by Seeelefant** [ArduPilot/ardupilot#13171]
Bug report
FrSky Telemetry on Kakute F7 AIO not working with the setting mentioned here http://ardupilot.org/copter/docs/common-holybro-kakutef7aio.html . RCIN and Telemetry are both configured on UART6. Is there some kind of Inverter or dedicated cable missing?

Issue details

RX6 <-----> S.BUS
TX6 <-----> S.PORT

image
![image](https://user-images.githubusercontent.com/30323691/71767391-21b75f00-2f0c-11ea-923e-c9a3ee26589c.png)

No telemetry data (by yapuu script)/no sensors dicovered.
Version
ArduCopter V4.0.0 (4969354)

Platform
[ ] All
[ ] AntennaTracker
[ X ] Copter
[ ] Plane
[ ] Rover
[ ] Submarine

Airframe type
X4

Hardware type
Holybro Kakute F7 (not AIO)

Logs
02.01.2020 18:24:47 : PreArm: Battery 1 low voltage failsafe
02.01.2020 18:24:47 : PreArm: Battery 1 low voltage failsafe
02.01.2020 18:24:47 : PreArm: Compass not healthy
02.01.2020 18:24:17 : RCInput: decoding SBUS
02.01.2020 18:24:17 : PreArm: Battery 1 low voltage failsafe
02.01.2020 18:24:17 : PreArm: Battery 1 low voltage failsafe
02.01.2020 18:24:17 : PreArm: Compass not healthy
02.01.2020 18:24:17 : PreArm: Throttle below Failsafe
02.01.2020 18:23:53 : Frame: QUAD
02.01.2020 18:23:53 : KakuteF7 00340018 32365101 30383430
02.01.2020 18:23:53 : ChibiOS: 1ed2b2e9
02.01.2020 18:23:53 : ArduCopter V4.0.0 (4969354)

**Comment by cglusky** [comment]
Have the same setup and tested to work with X8R and X4R.  Your params look fine.  This is a single wire/half duplex only so just SPort to TX6. 

Kakute will not power peripherals from USB and it will struggle to finish booting.  You need to have battery power applied.  Which means you should really remove props each time you want to plug into USB to make big changes.  I do anyway.  

I would also suggest you start a thread at discuss.ardupilot if it's not working as it's best place to get help.

**Comment by Seeelefant** [comment]
Dear all, I tried it again with all recommendations listed, however I still do not how any success. However I use the recent firmware from FrSky https://www.frsky-rc.com/important-firmware-update-accst-d16/ , is there some kind of interference?

**Comment by mattdholmes00** [comment]
seeelefant, any luck?  I too am having issues with a similar setup.  kakute f7 v1.5 (not the AIO version).  Interesting thing is that I'm successfully getting both the RX telemetry (not too exciting) AND the GPS telemetry, which indicates to me that the FC is actually passing something through properly.  But I'm not getting the other FC telemetry, e.g. battery/current etc.

details:

TX firmware on Taranis X9D+2019: ACCESS 2.3.10
RX firmware on R-XSR: ACCESS 2.1.0

Like you I have 
RX6 <-----> S.BUS
TX6 <-----> S.PORT

I also have: 
SERIAL6_BAUD=57
SERIAL6_OPTIONS=7
SERIAL6_PROTOCOL=10

My discovered sensors on the taranis include RSSI, RxBt, VFR, and GPS.  The first three come direct from the R-XSR RX, but the last one only started working when I configured the serial port for passthrough, so that makes me feel like I *almost* succeeded.

I have no errors in my logs.

I plug in the battery to test, props removed, to provide sufficient power.

I have not installed the Yaapu LUA yet, I was hoping to discover sensors before adding that layer.

**Comment by mattdholmes00** [comment]
Update: I started installing the yaapu LUA script (haven't got it working fully) but then when I re-discovered telemetry sensors, they all showed up...

**Comment by IamPete1** [comment]
sounds like this is resolved. I have a Kakute F7 somewhere where it was working.
