### ISSUE TITLE
RC16 minimum is greater than trim

### ISSUE THREAD

**Issue by abenn1** [ArduPilot/ardupilot#13255]
I'm new to Ardupilot, and am setting it up on a Pixhawk 2.4.8 in a hexcopter.  When connected to Mission Planner, and trying to arm my hex, I'm getting the above error message.  I've found the problem in other threads here, and I can see in my parameters list that RC16 (and all other RCs) trim is showing as 874 whereas minimum is 1100.  I also see that I can change the trim value, but whan I'm not sure about is (a) what value is recommended for trim and, (b) having changed it on the screen, how to I save it to my Pixhawk?  After editing the value, do I Save to file, Write params, refresh params, or some combination of all three?

Arducopter 4.0.0; Mission planner 1.3.70

#### Platform
[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
Hexcopeter

#### Hardware type
Pixhawk 2.4.8

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by rmackay9** [comment]
@abenn1, thanks for the report although normally it's best to raise these in the [Copter-4.0 support forum](https://discuss.ardupilot.org/c/arducopter/copter-40).

This was caused by an issue in Mission Planner's RC calibration which has since been fixed.  I think if you update the MP and re-do the RC calibration i t will be OK assuming that the transmitter you're using has 16 channels.  If it doesn't then I'm afraid you'll need to manually go into the full parameter list and change RCx_TRIM to 1500.
