### ISSUE TITLE
Copter: pre-arm check for GPS quality if flying in super-simple mode

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#1338]

**Comment by R-Lefebvre** [comment]
I would think this can be closed with the performance of current EKF?

**Comment by rmackay9** [comment]
I'm afraid we still don't specifically check the GPS based upon whether we're in super simple mode.  So if we're in super-simple with Alt-Hold.. that would not lead to a GPS pre-arm check.

**Comment by R-Lefebvre** [comment]
But doesn't current arming always check the GPS?  It seems fairly strict now.

**Comment by rmackay9** [comment]
@R-Lefebvre, it only checks the GPS if the vehicle's in a mode that requires the GPS or the circular fence is enabled.  So it's very possible to take-off without GPS lock in stabilize or AltHold.

**Comment by R-Lefebvre** [comment]
Trying to understand what I'm seeing... I normally cannot arm, even in Stab mode, unless the GPS is good. I also normally have Fence enabled, but set to "warn only".  Is this maybe why?  If I completely disable the fence it will arm?

If that is true, the problem is a little more clear to me.  I really think that if the GPS is plugged in, you should not be able to arm unless it has a good fix.

Errr... well I guess this bumps into the people who are flying from forest clearings and can't get a fix until they get up above the trees... :(

**Comment by rmackay9** [comment]
Pushing to AC-3.5.  We're simply out of time for AC-3.4.

**Comment by amilcarlucas** [comment]
The new mode refactoring makes this possible, right?
