### ISSUE TITLE
AP_Servo: allow do-set-servo commands to affect more SERVOx_FUNCTION

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#13478]
We should relax the check added in this PR https://github.com/ArduPilot/ardupilot/pull/9107 so that users can use do-set-servo to affect the outputs for those outputs where this is safe.

One user has requested do-set-servo commands be effective for the sprayer ([discussion](https://discuss.ardupilot.org/t/do-set-servo-in-spray-function-does-not-work-in-4-0-0/51950))

Here is a list of [SERVOx_FUNCTIONs](https://github.com/ArduPilot/ardupilot/blob/master/libraries/SRV_Channel/SRV_Channel.h#L45) that we could potentially enable do-set-servo commands to affect:

- k_sprayer_pump
- k_sprayer_spinner
- k_gripper
- k_landing_gear_control
- k_cam_iso
- k_cam_aperture
- k_cam_focus
- k_cam_shutter_speed

These definitely can't be updated by do-set-servo because the feature constantly writes the latest value:

- k_starter
- k_ignition
- k_winch

I'm unsure if we want to allow k_scripting1 .. k_scripting16 to be updated so this is a question for @WickedShell.

These seem to be unused functions that we should remove from the parameter descriptions at least:

- k_egg_drop (called "release" in param descriptions)
- k_choke

**Comment by WickedShell** [comment]
This was actually intentional, though we actually talked about this kinda of case on the call. If we need a control mechanism for controlling the sprayer there should be explict commands for that. The servo relay events is weird because it easily crashes the vehicle, and is orthogonal to a libraries ability to actually control itself. This actually leads to weird problems where you toggle it, then the sprayer library may choose to move over it.

I'd personally prefer to see us not revert on this, and provide a more controlled/correct interface that the libraries are aware of when they need it.

**Comment by rmackay9** [comment]
@WickedShell, I generally agree but because the extra effort wasn't put in to provide an interface at the time the restriction was added users see a functional regression.

**Comment by rmackay9** [comment]
I'm going to close this because we've at least added the sprayer and gripper to the whitelist of functions that can be affected by do-set-servo
