### ISSUE TITLE
Pixhawk Internal Compass ID PreArm: compasses inconsistent in 3.2-RC6

### ISSUE THREAD

**Issue by svenp** [ArduPilot/ardupilot#1355]
I have updated all 3.2-rc2-rc6 versions to my pixhawk build in china.
But now after update to RC6 my compass does not wok anymore.
I have read the about the problems with the COMPASS_DEV_ID in RC5.
In RC5 the COMPASS_DEV_ID was 73225 for external and COMPASS_DEV_ID2 was -1 for internal.
Yesterday i updated to rc6 after a good flight with rc5. Then i do new compass and accel kalib,
My Pixhawk now says PreArm: compasses inconsistent.
So i take a look to the Full Parameter List.
COMPASS_DEV_ID now is 73225 and COMPASS_DEV_ID2 now is 131594
So i think there is my Problem, COMPASS_DEV_ID2 is wrong.
When i do a Prearm Skip Compass, i can fly in Stablize and AltHold. 
Is it possible the is a ID Check Problem in RC6?
Regards 
Sven

**Comment by sn0west** [comment]
I do have exactly the same problem as described. But I'm pretty shur my board and external compass are heading the same direction. 

I get twice the same ID on Compass_dev_id and Compass_dev_id2. so AC 3.2.1 see that there are two of them but gives the same ID and so I get a prearm compass not kalibrated.
Two days ago everything was fine an I could perfectly fly in Loiter. 
I didn't touched the copter since thrn, pluged the usb to my AUAV-X2 and then compass error. 
My compass is the one frome drotek the big one with XL M8N.

Please tel me where is the bug.
Thanks

**Comment by sn0west** [comment]
Anyone?

**Comment by rmackay9** [comment]
@sn0west, a log is required I'm afraid.  Best to post it into the APM Forum.  maybe drop a link here so I see it.

**Comment by sn0west** [comment]
Hi, I post this topic in the apm forum, but without any responce. 
Due to this problem I did not fly, so no logs with this specialy problem. Do you want so see the parameter list and maybe a log from a previous flight, but there wasn't any compass problem. 
Yesterday I pluged back the usb cable, an the ac managed to set the dev id for both compass correctly. I didn't touched any setting or cable sind three days ago, where the problem occure. So it seems like other user as I read, that this dev_id problem is like come and go as it like.
Have you ever heard of this issue before?
I forced the ac to fly with only the external compass, but did not test it yet.

I would like to help you the best way I can to solve this problem, so I will post a dropbox link with a full parameter list and my last logs, wich was only flying in loiter.
Okay?

Thanks

**Comment by matt88** [comment]
Has anyone figured out this issue? I've got a pixracer not recognizing the external compass?
