### ISSUE TITLE
Mission planner issue

### ISSUE THREAD

**Issue by Vishranthee** [ArduPilot/ardupilot#13717]
I changed few parameters related to ESC caliberation and rebooted the vehicle from QGC. It started in mission mode and flew out of control.
Will a quad enter mission mode without any commands?

Version : Arductoper 3.6.9

**Platform**
[  ] All
[  ] AntennaTracker
[ X ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Quad X

**Hardware type**
Pixhawk

**Comment by rmackay9** [comment]
Hi @Vishranthee,

Support issues should really go into the support forums:

- [Copter-3.6 support forums](https://discuss.ardupilot.org/c/arducopter/copter-36/140)
- [Copter-4.0 support forums](https://discuss.ardupilot.org/c/arducopter/copter-40/155)

When you post it's best to provide an onboard log file.

I'm going to close this issue.  Sorry to be strict but if we're not then our to-do list (which is what this is) because a support forums.

Thanks for using AP!
