### ISSUE TITLE
AntennaTracker: altitude always displayed as zero in MP

### ISSUE THREAD

**Issue by nhadrian** [ArduPilot/ardupilot#1491]
Hi,

In MissionPlanner the tracker's altitude display shows continously 0.00, when connecting via USB.
Is there a BUG in Mavlink messages only or in Altitude measurement/calculation?

Adrian

**Comment by KtotheG** [comment]
Anyone else having an issues with pitch locking up around the midpoint once the tracker is in auto and powered up. Wondering if it's related to the altitude not updating. Works fine in scan but locks in auto

**Comment by KtotheG** [comment]
Anyone else having an issues with pitch locking up around the midpoint once the tracker is in auto and powered up. Wondering if it's related to the altitude not updating. Works fine in scan but locks in auto

**Comment by rmackay9** [comment]
I think the altitude is zero by design.  The idea being that the antenna tracker is always on the ground and not changing it's altitude.  The tracker read's from the barometer but I think the plan was for it to use that data to correct the vehicle's barometer drift (assuming the baro drift that the vehicle and tracker sees are the same).

I guess you all think the altitude should change?

**Comment by magicrub** [comment]
I agree with your methodology, Randy. For differential baro the ground
station must remain zero. Now if that is somehow breaking something then
that's a different topic.

**Comment by Naterater** [comment]
I think this is the correct behavior - the ground station should always be on the ground.
