### ISSUE TITLE
Plane: flap slew rate limit does not work for flaperons and d-spoilers

### ISSUE THREAD

**Issue by IamPete1** [ArduPilot/ardupilot#14931]
Flap slew-rate param only works for the dedicated flap and flap_auto servo functions. When flap is used in the flapperon and dspoiler mixer no slew rate is applied. 

Looks like a tricky fix, I think the best method would just be to refactor the slew rate servo channels function. The current function is only used by plane throttle and flaps.

**Comment by magicrub** [comment]
I think @samuelctabor has fixed this on our fork which we currently working on getting into upstream soon

**Comment by samuelctabor** [comment]
The problem is that the slew rate is applied in SRV_Channels rather than in servos.cpp. It's not easy to grab the slew rate limited value as the slew is done at quite a low level. In the KH fork I fixed it by replicating the slew rate limit code in servos.cpp and applying it to the argument of flaperon_update. 

A better solution would be to add a helper to get the slew rate limited output from SRV_Channels. Even better would be to distinguish between "basic" flight controls - aileron, elevator, throttle, rudder, flap and airbrake - and actuator outputs.
