### ISSUE TITLE
Does the code support cars with Mecanum wheel?

### ISSUE THREAD

**Issue by liu-jiaming** [ArduPilot/ardupilot#15181]
## Feature request

I'm working on the Mecanum wheel，I hope APM can support it.

**Platform**
[  ] Rover

**Additional context**
Here's a description of Mecanum Wheels：
https://www.vexrobotics.com/mecanum-wheels.html

**Comment by jmachuca77** [comment]
https://ardupilot.org/rover/docs/rover-motor-and-servo-connections.html#omni-vehicles

**Comment by liu-jiaming** [comment]
> https://ardupilot.org/rover/docs/rover-motor-and-servo-connections.html#omni-vehicles

This is my car,it's the second type of page, right?

![123456](https://user-images.githubusercontent.com/70355870/91522043-d125c380-e92b-11ea-8fc8-d75767998a73.jpg)

![456789](https://user-images.githubusercontent.com/70355870/91522360-9e2fff80-e92c-11ea-8d4f-f4b54e419bc0.png)

**Comment by rmackay9** [comment]
@liu-jiaming, yes, it should be the middle one.  The OmniX.

By the way, AP's support of Omni vehicles is not quite complete.  So you'll find you can move the vehicle laterally in manual mode but not in other modes.  So for example in Autonomous modes the vehicle will continue to steering back towards the line between waypoints instead of moving sideways towards the line.

**Comment by jordancormack** [comment]
@rmackay9 is that still the case?

I'd like to build something with a similar motor configuration, but want to move laterally in auto mode, without changing heading.

**Comment by geofrancis** [comment]
yes unfortunately.
