### ISSUE TITLE
Will ardupilot support adrc control algorithm

### ISSUE THREAD

**Issue by moluav** [ArduPilot/ardupilot#15625]
## Feature request

Recently, I watched some videos related to ADRC control, and it seems to be much better than PID control. I'm not good at algorithms, so I can't figure it out. Will ardupilot support the adrc automatic control algorithm in the future?
**Platform**
[* ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by khancyr** [comment]
Hello,

If somebody can implement it and prove that it is better than our current solution, maybe. Otherwise, no.

There are plenties algorithms that can be better than PID but they need to be carefully tested  against performance/ressources used/setup complexity etc.

So asking for a random algorithms to be support in the future will always be a maybe. No guarantees
