### ISSUE TITLE
YAW behaviour sometimes ignores ROI during mission

### ISSUE THREAD

**Issue by CarManBelarus** [ArduPilot/ardupilot#16137]
## Bug report

**Issue details**

pixhawk board, flying mission, copter nose position resets sometimes, do not wollow POI. I use 2D gimbal . drone moves nose forward it movement, not POI, after passing some waypoints. I set POI in mission planner manually, it flies normally for some time, and then resets again.

for example, for log#2 :  after WP 32 drone must still look at POI 29, turning slowly to the left, but it turned right to the direction of movement…  

What i wanted to be and what i have in simulation, using tha same waypoints, copter moves to the top of map and looks to the bottom:
![Simulation](https://user-images.githubusercontent.com/24219338/103148668-505cc400-4773-11eb-9cc3-65d672440537.png)

What I have in fact - it looks in the same direction as moves: 
![tlog-1](https://user-images.githubusercontent.com/24219338/103148669-52268780-4773-11eb-9265-292d7461348b.png)

**Version**
4.0.4, 4.0.5

**Platform**
[  ] All
[  ] AntennaTracker
[ X ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
quadcopter

**Hardware type**
Pixhawk

**Logs**
case 1 : [2020-10-30 11-13-37.zip](https://github.com/ArduPilot/ardupilot/files/5742878/2020-10-30.11-13-37.zip)

case 2 : [2020-12-11 10-57-09.zip](https://github.com/ArduPilot/ardupilot/files/5742874/2020-12-11.10-57-09.zip)

**Comment by rmackay9** [comment]
This is really a support issue so it should be raised in the [support forums](https://discuss.ardupilot.org/c/arducopter/copter-40/155) rather than here in the issues list.  Sorry to be strict but if we're not then our to-do list turns into another support forum.

I think the issue is the RC4 input has some glitches in it.  It might be good to invest in a better receiver or perhaps increase the RC4_DZ parameter to 40.
![image](https://user-images.githubusercontent.com/1498098/103190147-0ad6fd00-4913-11eb-942c-62f159aed2c5.png)

**Comment by CarManBelarus** [comment]
> This is really a support issue so it should be raised in the [support forums](https://discuss.ardupilot.org/c/arducopter/copter-40/155) rather than here in the issues list. Sorry to be strict but if we're not then our to-do list turns into another support forum.
> 
> I think the issue is the RC4 input has some glitches in it. It might be good to invest in a better receiver or perhaps increase the RC4_DZ parameter to 40.
Thank you! I will try it. Why I posted here is because the problem appear after update to 4.0.4, never head to such problems with 3.x.x with the same hardware
