### ISSUE TITLE
4.0.6.rc1 Quad shoots into air when switched to AltHold: Probably an issue with EK3

### ISSUE THREAD

**Issue by NitinJSanket** [ArduPilot/ardupilot#16148]
Issue details

The quadrotor shoots into the air with full throttle when switched from Stabilize to AltHold or Loiter. Using TFMini lidar indoor without GPS on a Holybro Kakute F7.

Version
4.0.6.rc1

Platform
[ ] All
[ ] AntennaTracker
[ x ] Copter
[ ] Plane
[ ] Rover
[ ] Submarine

Airframe type
Quad X4.

Hardware type
Holybro Kakute F7

Logs
https://drive.google.com/file/d/1YiMtv_jK7PZo-0LnQXtjZay-OFNNc5YN/view?usp=sharing

It seems like the altitude value is shooting to -150.
![103164807-bd0ca880-47dd-11eb-911e-6ee35d739a14](https://user-images.githubusercontent.com/12091857/103166378-5ee8c100-47ef-11eb-8e81-65c409094e59.png)

I'm pretty sure it's not a user bug. I am attaching a few more snapshots. The AHR2 altitude looks perfect but the CTUN Alt is garbage.

![103166331-f0a3fe80-47ee-11eb-98e9-1ea4dfa249ce](https://user-images.githubusercontent.com/12091857/103166379-60b28480-47ef-11eb-8ae2-c8fb20b62c59.png)
![103166322-e71a9680-47ee-11eb-8c5c-295d2530afaa](https://user-images.githubusercontent.com/12091857/103166380-61e3b180-47ef-11eb-8519-57e275b2d5e8.png)

**Comment by andyp1per** [comment]
Can you post a .bin file. Most likely explanation is vibration. But best to ask these questions in the forums.

**Comment by NitinJSanket** [comment]
Here's the bin file: https://drive.google.com/file/d/1BOaGTTJEUP5UhDzIhoso3NpnNW8PG2ZC/view?usp=sharing
I did do a check for vibrations and they seem to be under 30 all the time.

**Comment by NitinJSanket** [comment]
> Can you post a .bin file. Most likely explanation is vibration. But best to ask these questions in the forums.

Here's the bin file: https://drive.google.com/file/d/1BOaGTTJEUP5UhDzIhoso3NpnNW8PG2ZC/view?usp=sharing
I did do a check for vibrations and they seem to be under 30 all the time.

**Comment by andyp1per** [comment]
Too much vibration IMO, if you look at IMU.AccZ the variation is huge - that's going to cause the EKF a lot of issues

**Comment by rmackay9** [comment]
I agree that the issue is probably vibration although the vibe message isn't terrible and the clip count is low.

The setup is a bit unusual in that the EK3_ALT_SOURCE has been set to 1 (rangefinder) which is nearly always a bad idea.  It's also using EKF3 and optical flow though so perhaps it is an indoor environment.

In any case this is really a support issue so it should be posted in the forums. https://discuss.ardupilot.org/c/arducopter/copter-40/155.  Sorry to be strict but if we're not then our to-do list turns into another support forum.
