### ISSUE TITLE
Quadplane/wrong initialization of landing gear/mount retract outputs

### ISSUE THREAD

**Issue by nhadrian** [ArduPilot/ardupilot#16264]
## Bug report

**Issue details**

When configuring 29:LandingGear or 9:mount_open for a servo output, after booting up it is initialized wrong, output value is 0 instead of configured minimum pwm. This only happens when Quadplane is enabled (Q_ENABLE=1), otherwise initialization is properly done. After changing output state either manually or with configured altitude for LGR, output gets correct value and after it works properly.

**Version**
4.1.0.0

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ X ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Quadplane

**Hardware type**
SITL

**Logs**
_Please provide a link to any relevant logs that show the issue_

**Comment by IamPete1** [comment]
Spent a little while trying to trace this. It can be fixed by moving the landing gear and mount init functions after quadplane setup in `init_ardupilot()`. However I cannot get to the bottom of exactly what is causing it, I think its to do with trying to assign the defualt motors outs for Quadplane.
