### ISSUE TITLE
Copter: support cw, ccw field of condition_yaw

### ISSUE THREAD

**Issue by GrahamDyer** [ArduPilot/ardupilot#1640]
Currently condition_yaw behaves like this:
*Copter facing north (0°) when armed, CCW = counter clock-wise:

Condition_yaw, 90°, CW, abs (0) = copter yaws 90° CW to face east (correct)
Condition_yaw, 270°, CW, rel (1) = copter yaws 90° CCW to face north (not 270° CW to face north!)

Condition_yaw, 90°, CCW , abs (0) = copter yaws 90° CW to face south (not 90° CCW to face north)
Condition_yaw, 270°, CCW, rel (1) = copter yaws 90° CCW to face north (not 270° CCW to face south!)

Condition_yaw, 90°, CW, abs (0) = copter yaws 90° CW to face east (correct)
Condition_yaw, 90°, CCW, rel (1) = copter yaws 90° CW to face south (not 90° CCW to face north! Same as previous)

So to fix this:
a) the copter needs to turn in the direction of the amount of degrees, so +270 should turn clockwise 270° not 90° counter clockwise to achieve 270°
or
b) CCW/CW instruction needs to be adhered to.

**Comment by GrahamDyer** [comment]
So speed of rotation and the CW or CCW instruction do not work, I'll leave this open then.
In my application I need the çopter to do a slow 90° or 180° or 360° rotation (1-5 deg/sec) in a certain direction, this is not currently functioning.

**Comment by robustini** [comment]
+1

**Comment by chris669** [comment]
Hi, one point with CONDITION_YAW, does the command need to be "sandwitched" between waypoints? Each time? My syntax is:
WAYPOINT 1
CONDITION_YAW 90°  it works
WAYPOINT 2 it cancel the last CONDITION_YAW

So my question is, after each waypoint, I have to add a new CONDITION_LAW?
In my small bain, I could imagine something like:

WAYPOINT 1
CONDITION_YAW 90° 
WAYPOINT 2
WAYPOINT 3
WAYPOINT 4
CONDITION_YAW 0°  (or stop CONDITION_YAW)

Does it make some sense for other people than me?

Thanks for reading.

chris

**Comment by rmackay9** [comment]
@chris669, after each waypoint, by default the yaw will return to the WP_YAW_BEHAVIOR.  So if you set that to "0" for example it will never try to control the yaw as part of the mission and it will continue to obey the condition-yaw commands across waypoints.  Alternatively we could change it so that it always continues to obey the condition-yaw across waypoints but we'd need to figure out a way for the user to specify explicitly that they want the behaviour to return to the default.

**Comment by chris669** [comment]
Ok, thanks, I had WP_YAW_BEHAVIOR : 3 in my config, I will try it ASAP. I know that it's very difficult to satisfy everybody, and do not know what would be the best procedure to validate such "nice to have" features. Maybe listing what are the possibilities, and let the user choose if it's not possible to easy set a new parameter for this. Or define a group of beta testers? Another point, I've seen in the MP interface that by default the field "Dir" is set to 0. And then, in documentation http://copter.ardupilot.com/wiki/mission-command-list/#condition-yaw we have two possibilities for the value 1 and -1: (1=CW, -1=CCW)  Used for a relative yaw. True values for this parameter is 0,1 or -1,1 ??? Thanks anyway for the good job, I will stay available for testing. A nice day.

**Comment by waTeim** [comment]
Following up here from the referenced dronekit issue.  When operating in *GUIDED* mode, there is a need to control the yaw rate so that yaw angle transitions are not perceived to hitch from one angle to another, but rather smoothly and if possible continuously transition.  This seems to be a longstanding limitation and related (in addition)  to #1635, #1758, and #4134.

**Comment by IamPete1** [comment]
closed by https://github.com/ArduPilot/ardupilot/pull/17539
