### ISSUE TITLE
Copter/Sub/Plane/Rover: should we send message_item_reached message in Guided?

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#16806]
PR https://github.com/ArduPilot/ardupilot/pull/16796 brought to light the small issue that our vehicles are inconsistent in whether they send message_item_reached messages when they reach a Guided mode target.  Copter and Sub do not.  Plane and Rover do.

This question was raised by @jmachuca77

**Comment by amilcarlucas** [comment]
Yes, adding support in Copter and Sub would make a lot of users happy :)

**Comment by jmachuca77** [comment]
I believe for guided mode it is important to send that message in all vehicles. Its the only feedback a user has to know that the target they sent was actually reached. A companion computer running a script will want to know when it should send the next target for example. 
In the case of auto mode, I don't think its as critical because AP is in control and will send the next waypoint automatically. But for consistency I would also add it. That way again, if a companion computer is monitoring the progress of a mission it could potentially use those messages to know when AP reached the target.

**Comment by amilcarlucas** [comment]
Can it be refractored into AP_Vehicle ?
