### ISSUE TITLE
Copter:Pitch automatically raised after arming in ArduCopter 3.2stable. 

### ISSUE THREAD

**Issue by touma-setsuna** [ArduPilot/ardupilot#1745]
After Pixhawk is armed,HUD shows the pitch raises automatically, for about 5 - 10 degree. From  power on to this problem occurred, the board haven't been touched or moved.(powered by PM). Two screenshots may show this problem clearly. 

![before](https://cloud.githubusercontent.com/assets/10434996/5647020/0c815af6-96bd-11e4-806b-8662e12b9547.jpg)
Before arming, the HUD shows the board is level.

![after](https://cloud.githubusercontent.com/assets/10434996/5647171/71efce6c-96be-11e4-8b2a-873bb4f9d7de.jpg)

After armed, the HUD shows the nose of board is pitching up slowly, then stops in the postion of about 5-10 degree up. 

During this, the board stays level itseif. 

And this WON'T occur in firmware 3.1.5.  A friend of mine finds this bug as well.

**Comment by R-Lefebvre** [comment]
Which AHRS system are you using, DCM or EKF?

**Comment by touma-setsuna** [comment]
DCM. I'm trying to upload my log files but failed many times. Great Firewall may be the cause.

**Comment by R-Lefebvre** [comment]
Jonathan, do you have any idea on this one?

**Comment by rmackay9** [comment]
This will likely be related to two things:
1. the difference in the accelerometer weighting between armed and disarmed (the accels are more heavily weighted when disarmed)
2. the gyro biases are recalculated at the first arming.
The shift in attitude will be because the gyro biases are pulling the attitude solution in one direction while the accels are pulling in the other.  when the accels become less weighted the solution moves towards the gyros.

Why the gyro biases are off is probably the underlying question.  My guess is if you leave the vehicle for a few minutes and arm again the attitude won't shift.
