### ISSUE TITLE
Copter: PSC.VX "vibration"

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#17702]
Copter-4.1 with SCurves is showing a sort of "vibration" in the position controller target position.
![psc-vibration](https://user-images.githubusercontent.com/1498098/121171953-20712b00-c892-11eb-832a-6baf3a08766a.png)

@lthall believes these are coming from the EKF and we do see small regular jumps in the position estimate as shown below.
![image](https://user-images.githubusercontent.com/1498098/121174539-fb31ec00-c894-11eb-85ab-fa3397acb4a0.png)

This can be reproduced in SITL quite easily by creating a mission with a long straight segment.
![sitl-vx-vibe-mission](https://user-images.githubusercontent.com/1498098/121171821-f6b80400-c891-11eb-9518-06bc8a9b1e34.png)

**Comment by priseborough** [comment]
I don't believe this is an EKF issue. If we log the PSC data at 400Hz and inspect the position as received by the controller, no noise is seen in the position, eg:

Here's the 'buzz' in demanded velocity:

<img width="1076" alt="Screen Shot 2021-06-09 at 8 05 04 pm" src="https://user-images.githubusercontent.com/3596952/121336444-db66fa80-c95e-11eb-8b30-e6635c43eee0.png">

Here's the target and measured position:

<img width="1023" alt="Screen Shot 2021-06-09 at 8 13 03 pm" src="https://user-images.githubusercontent.com/3596952/121336684-1b2de200-c95f-11eb-9f0e-42b0798a994b.png">

**Comment by rmackay9** [comment]
Ok, thanks.  It seems likely that the little jumps I show in the position graph above are because I'm graphing line number vs position instead of time vs position.

**Comment by lthall** [comment]
![image](https://user-images.githubusercontent.com/100896/121440876-e86c0400-c9c7-11eb-96b6-74ff5a266324.png)

You can see when I differentiate the aircraft position the rate of change of that position varies a lot from sample to sample. I suspect this has something to do with the ekf using different numbers of samples and therefore different delta times while the position controller is assuming a uniform time....

**Comment by lthall** [comment]
Close up:
![image](https://user-images.githubusercontent.com/100896/121441774-9330f200-c9c9-11eb-9611-17715ddc174b.png)

**Comment by lthall** [comment]
Could this be something like the time the ekf is calculating the position at is not the time of the next expected 400 Hz loop?

As the EKF update time and 400 Hz time moved together and apart it may look something like this....

**Comment by priseborough** [comment]
@lthall The EKF inertial nav in the output predictor is using a downsampled data product that on each autopilot atomic time step is using a different number of contributing IMU samples. For example if down sampling from 1000Hz sensor data to 400Hz autopilot rate, the number of samples will alternate between 2 and 3. As such the EKF output is correct at the time stamp of the IMU data it receives. Possible solutions include:

1) Change the autopilot or IMU sample rate so that the IUMU sample rate is a integer multiple of the autopilot
2) Time stamp the EKF solution passed via the ahrs or inav interface using the timestamp of the latest IMU sample that was used by the EKF. The position controller would then need to account for the irregular time step.

**Comment by lthall** [comment]
@priseborough Yeh I suspect the best approach is the translate the kinematics from the last ekf timestamp to the expected timestamp of the current fast loop. Given this results in a small 200 Hz noise signal the filters do a good job of removing it. So it isn't something that will crash aircraft.

**Comment by peterbarker** [comment]
I'm a bit confused as to why the 10Hz log doesn't have these artifacts.  The 10Hz log should simply be a subsampled version of the 400Hz log AFAIK - and yet it doesn't have the same furry spots - 'though it still has the associated discontinuities.

**Comment by lthall** [comment]
A 10 Hz log will have the same artifacts but they will be more difficult to see because you only have a 50% chance of getting the offset value when the fuz is present and then you only get 1 every 40 samples so the change in line slope almost disappears.

Talking through this with Randy I think the best approach moving forward is to move the time horizon of the position and navigation controllers back to the last EKF update time. This will then remove the problem of both timing jitter in the EKF update and the scheduling of the 400 Hz fast loop.

Filters will then be run with a timing jitter but this can be treated as noise.

This would mean that we must pass the time since the last EKF update acted on during the fast loop, into all objects that integrate or differentiate anything. So most PID objects and all attitude, position and navigation objects.

**Comment by lthall** [comment]
I wonder if this will be solved with the increase in precision of the position variables.

**Comment by rmackay9** [comment]
@lthall,

The vibration still appears I'm afraid.
![image](https://user-images.githubusercontent.com/1498098/127607561-24ec5756-1519-49b0-b5a6-c24dec1918c6.png)

By the way, for others watching, this reproduction of this issue requires moving these three lines found in Copter.cpp from the "ten_hz_logging_loop()" to the "fourhundred_hz-logging()" method.

```
    if (should_log(MASK_LOG_NTUN) && (flightmode->requires_GPS() || landing_with_GPS() || !flightmode->has_manual_throttle())) {
        pos_control->write_log();
    }
```

**Comment by lthall** [comment]
I think we can close this. This is a 1cm/s noise at a very high frequency (something like 200 Hz). The E filter in the velocity controller will all but remove this.
