### ISSUE TITLE
Copter: allow flying to waypoint's horizontal position first regardless of alt (non-linear path in 3D)

### ISSUE THREAD

**Issue by ForesterDev** [ArduPilot/ardupilot#18157]
## Feature request

**Is your feature request related to a problem? Please describe.**
Improvement of waypoint movement

**Describe the solution you'd like**
Currently waypoint movement for copter based on direct vector from current position and target. So if copter is near the the X/Y but is far from altitude - it will not run horizontal and only have vertical motion. I need a mode, when copter will fly horizontally until it reaches the target, and then change altitude vertically if it has not reached an altitude earlier

**Describe alternatives you've considered**
![movement](https://user-images.githubusercontent.com/11771800/127486434-25337c8b-ecb3-4ebe-8e33-05dd5850a5f4.png)

I tried to show graphically. On first image - the current behavior, and on second - what i need

**Platform**
[  ] All
[  ] AntennaTracker
[x] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Comment by IamPete1** [comment]
Can you not just add a intermediate waypoint?

**Comment by rmackay9** [comment]
I've updated the title to try and make it a bit clearer.

I wonder if you could clarify the situation this would be useful?  In general I don't think this is a good method because the operator won't know in advance the path that the vehicle will take.  Depending upon the environment (wind, battery voltage, payload weight) the path could change... I also don't think that the vehicle will reach its destination any faster.

.. still, thanks for the request.  It is interesting to think about.

**Comment by lthall** [comment]
Are you able to use guided mode to achieve this?

**Comment by lthall** [comment]
This is the behaviour you will see using guided pos, vel, accel input and keeping the vel and accel set to zero.

**Comment by IamPete1** [comment]
No response on suggested alternatives, so I'm going to close.
