### ISSUE TITLE
Not doing the MTD test on FMUv3 in rc.apm

### ISSUE THREAD

**Issue by gmorph** [ArduPilot/ardupilot#1945]
The if test is specifically checking for FMU v2 - this needs to be fixed.

**Comment by OXINARF** [comment]
I think this wasn't already the case when this was opened (last version before this was opened doesn't have any board check: https://github.com/ArduPilot/ardupilot/blob/ab96e988158f6eff2b4ae208ce553de6d4971765/mk/PX4/ROMFS/init.d/rc.APM#L374-L390), but it certainly doesn't happen today - this check has been moved to code instead of init file: https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_HAL_PX4/Storage.cpp#L200-L209.
