### ISSUE TITLE
Request for Download of Windows USB driver for PX4 in Mission Planner

### ISSUE THREAD

**Issue by ghost** [ArduPilot/ardupilot#195]
Hi Michael,

It looks like everything else we need for the PX4 is now in Mission Planner, but we also need the special (dual port) Windows USB driver.

If that could be directly loaded (and possibly even installed) directly from the Mission Planner firmware window, that would pretty well complete the package without requiring any additional steps.

Too bad days are only 24 hours long.

**Comment by rgbatson** [comment]
Mission Planner does not install PX4 on my laptop; six tries!

**Comment by magicrub** [comment]
What do you mean "does not install PX4"? It should load the Pixhawk driver.
Have you tried to download the px4 driver from the px4 site
<https://pixhawk.org/firmware/downloads>?

**Comment by rgbatson** [comment]
As I said. Mission Planner does not install driver. When I go to load firmware, I constantly get error 'Com4 does not exist". Further, Device Manager does not show it.
The site you refer me to does not work either - https://github.com/diydrones/ardupilot/issues/195#issuecomment-91633274
I click on the download for the driver and it attempts to display as text in my browser - goobledeygook of course since it is code. It does NOT download, like everything else, in my 'download' folder.
I wish you would send me an msi file for installing the driver.
Thanks you
Bob Batson
 
Date: Fri, 10 Apr 2015 10:48:17 -0700

**Comment by rgbatson** [comment]
The site https://pixhawk.org/firmware/downloads is the one I meant to mention as not working. This turns out to be the case only in my Firefox. I just ran it okay from Internet Explorer. I get a finish message with a list of drivers that are installed ok.
BUT Device Manager tells me they are NOT installed. So now I have the msi file, but still np installed drivers . . .
 
Date: Fri, 10 Apr 2015 10:48:17 -0700

**Comment by magicrub** [comment]
sounds like you're having typical Windows drivers problem that are
unrelated to our particular driver. Have you tried uninstalling, rebooting,
and reinstalling the driver?

**Comment by rgbatson** [comment]
I have tried everything I could research for days. Since I cannot go forward without this, I am at wits end.
Any further suggestions?
What OS do you use? 
Thank you for your time and consideration.
Bob Batson
 
Date: Fri, 10 Apr 2015 11:42:15 -0700

**Comment by rgbatson** [comment]
Tom,
PLEASE what else can I do. You refer to typical windows driver problems. Well, what else should I use. What do you use?
I am dead in the water with a $1,000 model all told.
Thanks
Bob Batson 
 
Date: Fri, 10 Apr 2015 11:42:15 -0700

**Comment by rmackay9** [comment]
It's probably not helpful but here are two mission planner and usb driver wiki pages.
http://copter.ardupilot.com/wiki/common-install-mission-planner/
http://copter.ardupilot.com/wiki/common-apm-usb-driver/

The second one is related to driver problems when using an APM board which I understand is not what you're using but perhaps some lessons can be learned from that page.

**Comment by meee1** [comment]
Please provide the file

C:\windows\dpinst.log.

 

Michael

**Comment by rgbatson** [comment]
Please note that I am successfully able to connect USB cable from 915 MHZ, and the computer will load/run correctly on COM4.
It is the PX4 file that does not install/load.
 
Date: Sun, 12 Apr 2015 16:29:05 -0700

**Comment by rgbatson** [comment]
Michael,
Thank you for your willingness to look at that log. I hope it pinpoints something that can be solved.
Bob Batson
 
Date: Sun, 12 Apr 2015 16:29:05 -0700

**Comment by meee1** [comment]
the log shows the driver are installed correctly, so any issue you are having is most likerly hardware.

**Comment by rgbatson** [comment]
Thank you again. Can you tell which hardware? Do I need a new laptop?
Bob Batson 
 
Date: Sun, 12 Apr 2015 20:26:11 -0700

**Comment by mechfishy** [comment]
Hi,

This seems to be an ongoing issue for a lot of people.  I just "upgraded" I thought.  Now I want to chuck it in the trash because I am extremely frustrated.  Upon first connect I had no problem at all.  Mission Planner automatically installed the necessary drivers.  However the next attempt and now the thirty other attempts have not worked.  I have many different types of flight controllers, including some brushed types.  If I update a F3 board, the next time I want to update a Naze 32 board I have to go through a very specific process to reload the correct drivers.  You can't just uninstall and reinstall the usb drivers.  You first have to start the the universal serial something.  I don't recall right off hand.  Something to do with DFU mode.  Then you have to set up another driver in the universal serial bus controllers and then finally after those steps you can then set up the actual driver for the com port.  So I am suspecting this is a similar condition, because I can almost get there, but with the yellow triangle.  So obviously there is a step I'm missing somewhere.  Perhaps I have to update the px4dfu in the first step and then maybe the 3DR in the universal serial bus controllers before I can get the px4 com port installed correctly.  I don't know exactly what those steps are.  But like I said earlier I believe it has something to do with having those other drivers interfering with the proper installation of the PX4 drivers.  Windows might not know how to distinguish the difference between all these different boards.  I would really like to try this "upgraded" board, but I have to get it set up and tuned properly first.  So one of you brainiacs could really help a lot of folks out.  I am sure that once there is a universal solution for this, that it will then spread like wildfire and have thousands of views on youtube within a very short time.

**Comment by OXINARF** [comment]
@mechfishy This is a very old issue and Mission Planner issues don't belong here anymore. Also, this issues list is for feature requests and confirmed bugs. For user support please post in the forum (http://discuss.ardupilot.org).
