### ISSUE TITLE
 When GPS Lost, the fail safe don't work fine, but in this firmware does no work servos!

### ISSUE THREAD

**Issue by vmv007** [ArduPilot/ardupilot#19856]
## Bug report

**when the quad loses gps signal in auto mode, it switches to althold mode or land mode and start flying fast, and do not brakes**
**Version**
all stable firmwares, but "4.2.0 dev" working good
**Platform**

[  ] Copter

**Airframe type**
Quad

**Hardware type**
Pixhawk

**Comment by IamPete1** [comment]
We need a log to help diagnose this. https://ardupilot.org/copter/docs/common-downloading-and-analyzing-data-logs-in-mission-planner.html#downloading-logs-via-mavlink

**Comment by vmv007** [comment]
> We need a log to help diagnose this. https://ardupilot.org/copter/docs/common-downloading-and-analyzing-data-logs-in-mission-planner.html#downloading-logs-via-mavlink

Ok, but i already deleted log((( i will go to fly and get a new one

**Comment by vmv007** [comment]
> > We need a log to help diagnose this. https://ardupilot.org/copter/docs/common-downloading-and-analyzing-data-logs-in-mission-planner.html#downloading-logs-via-mavlink
> 
> https://drive.google.com/file/d/1jpons_JSS_THixdD0-Bnsg_jJUgLydYp/view?usp=drivesdk

**Comment by IamPete1** [comment]
That log is from 4.0.7, the current stable copter release is 4.1.3, please see if the issue remains on 4.1.3.

I'm not really sure what the issue is your having, looks like it switches to alt hold due to the EKF failsafe and then descends because the pilot input throttle is low? What behavior are you expecting?

**Comment by vmv007** [comment]
> That log is from 4.0.7, the current stable copter release is 4.1.3, please see if the issue remains on 4.1.3.
> 
> I'm not really sure what the issue is your having, looks like it switches to alt hold due to the EKF failsafe and then descends because the pilot input throttle is low? What behavior are you expecting?

other firmware same shit!
when althold is enabled, it should slow down and not accelerate!

**Comment by IamPete1** [comment]
In alt hold desired roll and pitch are zero. 

![image](https://user-images.githubusercontent.com/33176108/150693515-f0486b42-d99d-45ef-ae94-4f61a4c067f3.png)

I see no evidence of it accelerating in alt hold.

**Comment by vmv007** [comment]
> In alt hold desired roll and pitch are zero. 
> 
> ![image](https://user-images.githubusercontent.com/33176108/150693515-f0486b42-d99d-45ef-ae94-4f61a4c067f3.png)
> 
> I see no evidence of it accelerating in alt hold. 

the copter was flying on a slope and did not slow down when it switched to althold, i will try one more and will sent log here! When will be good weather

**Comment by IamPete1** [comment]
OK, I think I understand. The problem is not that is was trying to accelerate due to some failsafe action, just that it lost track of which way is up. We do see a difference in pitch between EKF and dcm.

![image](https://user-images.githubusercontent.com/33176108/150702103-7779dce1-645f-4960-b6ae-825011e92f0e.png)

Hard to tell which was right of course....

I suspect the difference you saw between 4.2 and 4.0 is EKF3 vs EKF2. 

Maybe you can test 4.1 with EKF3. 

I don't think there is a huge amount we can do in the code (not easily anyway). You could try and reduce your vibrations, that should help.

**Comment by rmackay9** [comment]
Rather than vibration I think it might be a GPS issue. If we look at the number of satellites and accuracies (see GPA message) it looks like it completely loses lock.
![image](https://user-images.githubusercontent.com/1498098/150703956-ad60e728-0a02-4785-91df-4c5ade2c8a07.png)

By the way, in AltHold mode the pilot controls the lean angle so it won't slow down on it's own.

At this point I think this issue is really a support issue.  Sorry to be strict but this should really be raised in the support forums first and then when we've confirmed it's a real bug or enhancement request we raise an issue here.  If we don't then our to-do list turns into a support forum.

I'll still be monitoring this thread for replies though.  Txs for the report.

**Comment by vmv007** [comment]
> Rather than vibration I think it might be a GPS issue. If we look at the number of satellites and accuracies (see GPA message) it looks like it completely loses lock.
> ![image](https://user-images.githubusercontent.com/1498098/150703956-ad60e728-0a02-4785-91df-4c5ade2c8a07.png)
> 
> By the way, in AltHold mode the pilot controls the lean angle so it won't slow down on it's own.
> 
> At this point I think this issue is really a support issue.  Sorry to be strict but this should really be raised in the support forums first and then when we've confirmed it's a real bug or enhancement request we raise an issue here.  If we don't then our to-do list turns into a support forum.
> 
> I'll still be monitoring this thread for replies though.  Txs for the report.

I used jamming gps, there are no problems with gps

**Comment by vmv007** [comment]
![Снимок экрана 2022-02-04 172901](https://user-images.githubusercontent.com/88681489/152556561-7b298100-c358-4c3b-a9a8-bfae03a040ac.png)
