### ISSUE TITLE
arducopter LOCAL_POSITION_NED returns values that not related to current HOME position

### ISSUE THREAD

**Issue by AleksandrBon** [ArduPilot/ardupilot#19974]
## Bug report

**Issue details**

I use ardupilot SITL simulator as described at [https://ardupilot.org/dev/docs/building-setup-linux.html#building-setup-linux](url)
I installed it long time ago with version of repo AP_Periph-1.0.0-3466-g10eeea31e8.
But yesterday I updated PC and installed the lates version of repo AION-Orca-Alpha2-6520-g189c4cc4c7
and found that NED coordinates that ardupilot sends in LOCAL_POSITION_NED not changing when I setting different home positions.

And i found that in old version function uses
`void GCS_MAVLINK::send_local_position() const
{
    const AP_AHRS &ahrs = AP::ahrs();

    Vector3f local_position, velocity;
    if (!ahrs.get_relative_position_NED_home(local_position) ||
        !ahrs.get_velocity_NED(velocity)) {
        // we don't know the position and velocity
        return;
    }
.............`

BUT newest one
`void GCS_MAVLINK::send_local_position() const
{
    const AP_AHRS &ahrs = AP::ahrs();

    Vector3f local_position, velocity;
    if (!ahrs.get_relative_position_NED_origin(local_position) ||
        !ahrs.get_velocity_NED(velocity)) {
        // we don't know the position and velocity
        return;
    }
......................`

But as described here [https://ardupilot.org/dev/docs/mavlink-get-set-home-and-origin.html](url) origin updated only once at system startup, and because of that in newest version NED coordinates not depending on HOME point.

Is this correct behavior? It is not stated anywhere that now NED is calculating relative to EKF origin. And Mavlink [https://mavlink.io/en/messages/common.html#LOCAL_POSITION_NED](url) also not specifies the origin for calculations.

From logic side this is right decision to have origin of NED set only once at startup, because if someone uses this NED data to build map and if NED origin is changed there will be map smashing. But on another side it is not stated anywhere what is the origin of NED calculations and that this function changes from release to release.

**Version**
"git describe --tags"
AION-Orca-Alpha2-6520-g189c4cc4c7

**Platform**
[  ] All
[  ] AntennaTracker
[x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
copter SITL

**Hardware type**
SITL

**Logs**

**Comment by hendjoshsr71** [comment]
Hi! I think this one can be closed. https://github.com/ArduPilot/ardupilot/pull/15169

Instead an issue (or PR) could be opened on [Mavlink/Mavlink ](https://github.com/mavlink/mavlink/issues) to fix the documentation issue to link to the `MAV_FRAME` for the `Local_NED` message.

The definitions for the MAV_FRAMES have recently been updated to be clearer with Frame, Origin, and altitude frames. See [here](https://mavlink.io/en/messages/common.html#MAV_FRAME)

`"LOCAL": Origin of local frame is fixed relative to earth. Unless otherwise specified this origin is the origin of the vehicle position-estimator ("EKF").`
