### ISSUE TITLE
Rover SITL: crashes if vehicle turns too quickly

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#20081]
I don't yet know if it is a Rover code issue or a simulator issue but the simulator crashes (or freezes) if the vehicle attempts a very high speed corner.  This can be reproduced by doing the following

- cd Rover
- sim_vehicle.py --map --console
- arm throttle (to arm in Manual mode)
- rc 3 2000 (100% throttle)
- rc 1 1000 (100% left steering)

![image](https://user-images.githubusercontent.com/1498098/153799811-3fee02de-8c71-45b1-b5e8-f7b70ff7f272.png)

![gdb-rover-sitl-failure](https://user-images.githubusercontent.com/1498098/153805513-5a53d502-ef92-4b17-9213-4b8330aac0a0.png)

**Comment by xianglunkai** [comment]
This PR always exists in Rover simulation. I checked the code, and consider that it is&nbsp;produces by&nbsp;calculation of simulation model,including the integral divergence caused by lack of kinematic and dynamical constraints. Maybe should provide KT model and dynamical water simulation calculations for ships
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人: "ArduPilot/ardupilot" ***@***.***&gt;;
 发送时间:&nbsp;2022年2月14日(星期一) 中午12:25
 ***@***.***&gt;;
 ***@***.***&gt;;
 主题:&nbsp;[ArduPilot/ardupilot] Rover SITL: crashes if vehicle turns too quickly (Issue #20081)

 

 

 
I don't yet know if it is a Rover code issue or a simulator issue but the simulator crashes (or freezes) if the vehicle attempts a very high speed corner. This can be reproduced by doing the following
  
cd Rover
 
sim_vehicle.py --map --console
 
arm throttle (to arm in Manual mode)
 
rc 3 2000 (100% throttle)
 
rc 1 1000 (100% left steering)
 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by IamPete1** [comment]
same as https://github.com/ArduPilot/ardupilot/issues/14469

Its not a rover issue, any vehicle will crash if you spin it fast enough. Just the rover sim is about the only way to get up to that speed.

**Comment by rmackay9** [comment]
OK thanks, closing this one then.
