### ISSUE TITLE
Numerical problem

### ISSUE THREAD

**Issue by liyue75** [ArduPilot/ardupilot#20284]
https://github.com/ArduPilot/ardupilot/blob/e94f28c81d099c322ee5b446ad68ca0180b34cf4/libraries/AP_AHRS/AP_AHRS_DCM.cpp#L268
I'm not sure should **10** be **1** here?

**Comment by hendjoshsr71** [comment]
This was discussed on the DevCall on 4/11/2022.

The bound 1.0 will be too low here. However, why 10.0 was selected vs a bound of say 2.0 was not known.
Given that there is not evidence of a current issue occurring, the risk of safety issues caused by a change here would not be worth the change.

Except if there is mathematical proof to go through the method of why the bound should be changed, and testing evidence to support the change.
