### ISSUE TITLE
It is possible to create two drivers for the same BARO

### ISSUE THREAD

**Issue by Williangalvani** [ArduPilot/ardupilot#20887]
The way AP_Baro.cpp is currently structured, a driver can be instantiated at [init()](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Baro/AP_Baro.cpp#L548-L762) and another one after probing if `BARO_EXT_BUS` and `BARO_PROBE_EXT` are set.

In my case, I had it probed [here](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Baro/AP_Baro.cpp#L713-L714) and [here](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Baro/AP_Baro.cpp#L883-L886)

![image (24)](https://user-images.githubusercontent.com/4013804/171523044-d6d6a97f-7c04-4453-ac8e-9952d1deaf79.png)
![image (23)](https://user-images.githubusercontent.com/4013804/171523050-102c0d57-9e55-416d-92a8-fa6f1d5612a7.png)

Tested using a Navigator (linux) board with ardusub master.

While this happened in a sub-specific block, it looks like it could happen with other boards mentioned in  [init()](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Baro/AP_Baro.cpp#L548-L762), too.

Could we maybe check if the devid is already registered?

**Comment by ES-Alexander** [comment]
A workaround for [the Sub-specific issue](https://discuss.bluerobotics.com/t/pixhawk-4-i2c-sensors-not-found/11507/7) is to un-set `ms5837` in `BARO_PROBE_EXT` since it's currently checked for automatically. That's unideal because it actively encourages unintuitive/incorrect behaviour, but good to at least have some way of getting the intended functionality working in the meantime.

**Comment by HefnySco** [comment]
@Williangalvani this issue should be fixed by [PR #20958](https://github.com/ArduPilot/ardupilot/pull/20958)
