### ISSUE TITLE
Rover: Throttle disarmed suddenly in auto mission!

### ISSUE THREAD

**Issue by xianglunkai** [ArduPilot/ardupilot#21731]
I don't know what the reason is, but suddenly the Boat/Rover is disarmed during auto mission

**Comment by xianglunkai** [comment]
By the way, I use the current master version.

**Comment by rmackay9** [comment]
@xianglunkai,

Txs for the report.  Could you post a log in the [Rover-4.3 forum](https://discuss.ardupilot.org/c/ardurover/rover43/168)?  As we always say, 'it's guess work without a log".

I'll go ahead and close this because if we're not strict about what goes into the issues list it just turns into another support forum.
