### ISSUE TITLE
CubeOrange adapting to ArduSub 4.1.0

### ISSUE THREAD

**Issue by aohihook** [ArduPilot/ardupilot#22161]
## Bug report
ArduSub cannot send water temperature data

**describe the problem_**
Cube Orange is equipped with two MS5611 sensors, which can output the pressure and temperature in the cabin. However, when connecting the MS5837 sensor, the sub firmware reconstructs the send_ scaled_ The pressure3 function only sends the temperature sensor of a specific model, but cannot send the water temperature data of the MS5837 sensor.
void GCS_MAVLINK_Sub::send_scaled_pressure3()
{
    if (!sub.celsius.healthy()) {
        return;
    }
    mavlink_msg_scaled_pressure3_send(
        chan,
        AP_HAL::millis(),
        0,
        0,
        sub.celsius.temperature() * 100,
        0); // TODO: use differential pressure temperature
}

**Version**
ArduSub-4.1.0

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[ √ ] Submarine

**Airframe type**
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

**Hardware type**
Cube Orange

**Logs**

**Comment by magicrub** [comment]
Closing since his code has recently changed in master to allow flexible temperature sources.
https://github.com/ArduPilot/ardupilot/blob/master/ArduSub/GCS_Mavlink.cpp#L97-L112

There's a new AP_TemperatureSensor library that I wrote a few months ago that allows you to route any temp data. Right now there's only 2 drivers but it's an enum that can be expanded to support, for example, routing anything that has a temperature such as a battery, airspeed sensor, ect ect. It also allows routing temp data from one library to another (for example, use the temp library to overwrite the battery or ESC temperature). Please take a look.
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_TemperatureSensor/AP_TemperatureSensor_Params.h#L29-L33
