### ISSUE TITLE
add "@RebootRequired: true" to params that need it

### ISSUE THREAD

**Issue by magicrub** [ArduPilot/ardupilot#2278]
Due to the varying complexity of params, some work instantly while others require a reboot to work correctly (or at all). To document this, lets add a "@ReqReboot: true/false" field to every param.

**Comment by rmackay9** [comment]
Related to this issue: https://github.com/diydrones/ardupilot/issues/2199

A great idea.

**Comment by magicrub** [comment]
here is a brief list of ones that need it
MOT_SPIN_ARMED
SERIAL*

**Comment by chapman** [comment]
+FRAME

**Comment by magicrub** [comment]
Lets do a tri-, or more, state scheme and change the label to @ "TakesEffectAt:" with possible values of "Immediate", "immediate while disarmed", "AtReboot"

**Comment by hsteinhaus** [comment]
Some params require a mode change to take effect, e.g. WPNAV_LOIT_SPEED

**Comment by magicrub** [comment]
Even while disarmed?

**Comment by hsteinhaus** [comment]
No, during flight. This behavior seems to be a thing between "immediate" and "immediate while disarmed". Some Auto-related params show the same behavior.

**Comment by magicrub** [comment]
So it takes effect while disarmed? Adding a forth "on mode change" may add
another layer of complexity that we like to avoid. I would vote to not have
that as a choice and to just roll out into disarm. The exception is of this
is something someone would like to change during flight.

**Comment by R-Lefebvre** [comment]
I think this issue with Loit Speed is an issue that needs to be fixed so it's immediate, rather than just documented and managed in the params.

**Comment by hsteinhaus** [comment]
Probably it will. I was never tempted to try that in the middle of a 1hour Auto mission, e.g. just for changing the WPNAV_SPEED from 8 m/s to 7 m/s after a wind change. It would be absolutely nasty (almsost show-stopping) if the GCS would force me to do more than a mode change here. 

IMHO the complexity is not added by describing the behaviour precisely, but by the behaviour of ArduPilot itself.

**Comment by magicrub** [comment]
As Rob said, we're better off changing the param to instant if we can fix
it to be so. Long-term goal is to get all params to do that where possible.

-TomP

On Tue, May 12, 2015 at 10:19 AM, Holger Steinhaus <notifications@github.com

**Comment by hsteinhaus** [comment]
Ok, that would be fine. But I think there is a whole bunch of parameters that show the same behavior because there is a very common pattern in the code. Those parameters are read one time when the flight mode is initialized and copied to local variables and/or used for initilializing other sub-components. If the param changes thereafter, there is no instant effect. I would not expect there will be an easy fix.

**Comment by R-Lefebvre** [comment]
Actually, I think most parameters will update their global variables immediately (probably all do).  The problem is some of the parameters get used to generate other static variables in init functions that only run on boot up.  We have been trying to move many of these init calculations into a periodic process that runs in the 1 second loop while disarmed.  But some are either tricky to do, or we don't want them to take immediate effect for other reasons.

For example, the loiter speed calc affects the leash length, which is only calculated once when initializing the mode.  Perhaps on Pixhawk, we could do this calculation all the time, but we'll have to look into that.

**Comment by rmackay9** [comment]
I've added this parameter description to the RCMAP parameters after svefro made it clear we should have this.
https://github.com/diydrones/ardupilot/commit/19b021f72922eda13508058a2895d31e11bdf164

**Comment by WickedShell** [comment]
This is needed for most of the GPS parameters, I'll submit the PR after the GNSS one is done.

**Comment by amilcarlucas** [comment]
This is better now

**Comment by magicrub** [comment]
We've done this in many places. Probably safe to close it for now
