### ISSUE TITLE
Arducopter_Simulink: ''Body Frame Rates -> DCM''  subsystem does no get same result as measure data

### ISSUE THREAD

**Issue by MarcLeclercGit** [ArduPilot/ardupilot#23295]
## Bug report
 The subsystem Body Frame Rates -> DCM seems to have a error when 
**Issue details**
Hi,

Using the simulink/adrucopter in the Tools repository I tried to validate that the simulink model would give me the same result as the Autopilot when using the same measured data.  When fed the measured desired roll rate/ pitch rate and yaw rate, the ''Rate Controller'' subsystem give the correct RATE out. When fed measured pitch angle data (simIn.param.attCtrlVal = true), the Attitude controller subsystem also  generate similar desired pitch and yaw rates as the measured one to use as input in the RATE controller. 

However, if I use the ''Body Frame Rates -> DCM '' subsystem and set the switch to use measured angRateBf for the operations from the sequence ''AP_AHRS_DCM::matrix_update() and Matrix3<T>::rotate()'' on it, I do not get the same ''attitudeBodyAct'' and ''eulerAngleAct'' as the measured data. I linked a image to where I did the comparison.
![BodyFrameRateDCM_Block](https://user-images.githubusercontent.com/70527789/226962832-8ae7befc-a7f2-4564-985f-747a3143dade.png)

The ''eulerAngleAct'' for Sim and Meas follow roughly the same trend, but the yaw sign is reverse

![image](https://user-images.githubusercontent.com/70527789/226965485-331f31d8-766b-4675-a64d-42cc693af207.png)

When I also compare the ''attitudeBodyAct'' the quaternions values from the Sim and Measured data follow the same shape but there's a significant offset between the values.

![image](https://user-images.githubusercontent.com/70527789/226966325-2a46e96a-a022-404a-be31-7b35425491ff.png)

I linked the flight log that I use for the comparison.I used the subflight when I was in AltHold.

Thanks

**Version**
Master branch

**Logs**
[Log_LineDroneJr_STAB_ALTHOLD_LOIT1.zip](https://github.com/ArduPilot/ardupilot/files/11042147/Log_LineDroneJr_STAB_ALTHOLD_LOIT1.zip)

**Comment by rmackay9** [comment]
This is one for @amilcarlucas or @fbredeme I think.

**Comment by fbredeme** [comment]
@MarcLeclercGit 
I tried the same setup (feeding in the measured body rates into the "Body Frame Rates -> DCM " subsystem) and I actually get quite satisfying results different from those deviations that your plots show. Can you post a screenshot that shows how you input the measured body rates?

**Comment by MarcLeclercGit** [comment]
@fbredeme 
Here's the screenshot on how I was feeding the measured body rates.
![Input_measure_bodyrate](https://user-images.githubusercontent.com/70527789/228840485-b01f8118-52fc-49e2-9c4f-dad6c7c08dd5.png)

**Comment by fbredeme** [comment]
I'm using the same setup as you do and I'm getting completely different signals, as you can see in the following plot for the euler angles (I put the scope at the exact same spot as you do):

![euler_angles_comparison](https://user-images.githubusercontent.com/92086379/229073237-f1027ad1-079d-4e18-9a66-d76a5006807b.png)

What's your setting for simInMode?

**Comment by fbredeme** [comment]
Yes you are right, I used the wrong subflight. But still, my results are different from yours. I can't open the model unfortunately, could you convert it to MATLAB version 2021a?

**Comment by MarcLeclercGit** [comment]
Ok, here's the Simulink code in the 2021a version
[arducopter.zip](https://github.com/ArduPilot/ardupilot/files/11138285/arducopter.zip)

**Comment by fbredeme** [comment]
Thanks for that. I tested your model for the loiter flight mode and the similarity between measured and simulated signals is still pretty satisfactory I'd say:
Euler angles:
![grafik](https://user-images.githubusercontent.com/92086379/230009616-84be845e-39c3-4f85-bb56-091e4e2db2b4.png)

Quaternions:
![grafik](https://user-images.githubusercontent.com/92086379/230009807-b63aa1f8-d8ea-464f-9016-e1200468fd8e.png)

The only thing I changed was using the "old" motor mixer subsystem since a parameter in the new one was missing in my model. I guess that is because you changed something in the sim_init.m.

It appears to me that something with your yaw angle is messed up. Did you change something for the initialization of the "ATT" signals in the sim_init.m? These are used to initialize the DCM matrix that is in return used in the Body Frame Rates -> DCM subsystem to calculate the euler angles and the quaternion.

**Comment by MarcLeclercGit** [comment]
I re-downloaded the repo from the master branch to take the original without any changed but I still obtain the same difference for the angles. I only added in the function folder ''fromAxisAngle.m'' and ''quatMult.m'' that were missing when running ''sid_sim_init''.  I don't understand why our results are different.

![image](https://user-images.githubusercontent.com/70527789/230392596-5f6c0d15-4ab2-43b3-97f0-978e7f57b208.png)
![image](https://user-images.githubusercontent.com/70527789/230392780-f4b7dcfb-78d2-4fb8-96a8-81ac85aab92e.png)

I attached the files ''sid_pre_repo.m'', ''sid_sim_init_repo'' and ''arducopter_repo_R2021a'' that I used. The only thing that I changed from the cloned repository is that I added the rotation order 'xyz' when the function 'dcmFromEuler' is called in ''sid_sim_init_repo.m'' since the function is expecting the 'order' argument. 
[sid_pre_repo.zip](https://github.com/ArduPilot/ardupilot/files/11171194/sid_pre_repo.zip)

**Comment by fbredeme** [comment]
I believe I know what causes the problem. In the 4.3 version of the simulink model, I forgot to add the functions "dcmFromEuler.m", ''fromAxisAngle.m'' and "quatMult". This was fixed for the version on the master branch. My "dcmFromEuler.m" does not possess any 'order' argument, so I don't know which function you are using. In my function, which is directly derived from the Ardupilot function "Matrix3<T>::from_euler", the rotation order is zyx. So try using my function instead of the one that you are using now.

**Comment by MarcLeclercGit** [comment]
I don't see the functions "dcmFromEuler.m", ''fromAxisAngle.m'' and "quatMult" in the 'functions' folder of the master branch.
Is it because it has not being merged yet?

**Comment by fbredeme** [comment]
Yes your are right, I thought that I already created a merge request for that matter. I will catch up doing that asap.

**Comment by fbredeme** [comment]
@MarcLeclercGit The merge request has just been approved and closed. The simulink version in the master branch should now work.

**Comment by amilcarlucas** [comment]
@MarcLeclercGit Can this be closed now?

**Comment by MarcLeclercGit** [comment]
Yes, you can close it.

Le lun. 4 déc. 2023 à 12:53, Amilcar Lucas ***@***.***> a
écrit :

**Comment by amilcarlucas** [comment]
No longer relevant
