### ISSUE TITLE
Follow the leader in MP

### ISSUE THREAD

**Issue by AlexandreLarribau** [ArduPilot/ardupilot#23395]
## Bug report

Hey ! I want to use the "follow the leader" module of Mission Planner. The location of both vehicles stays at 0 and nothing happens when we press start. Looks like buttons have been copied from the swarm module that works great but not in follow the leader.

My MP version is 1.3.8 build 1.3.8479.20539. 

I tried to make a copter following a rover in sitl. Works in swarm but not in follow leader so I think it is a problem with MP and not with the vehicles firmware. 

![image](https://user-images.githubusercontent.com/72812521/229797714-3712d636-5dde-4453-80d9-6db998ac8d2f.png)

**Comment by rmackay9** [comment]
This sounds like a Mission Planner issue so it should probably instead be raised in the Mission Planner issues list: https://github.com/ArduPilot/MissionPlanner/issues

I'll go ahead and close this issue because this is the flight code issues list.

By the way, here's a video of a Copter following a boat using Copter's follow mode. https://www.youtube.com/watch?v=Jc5rNZkB97s
