### ISSUE TITLE
Why do new objects not need to be deleted?

### ISSUE THREAD

**Issue by xianglunkai** [ArduPilot/ardupilot#23859]
for example:  AP_RangeFinder
 AP_RangeFinder_Backend *drivers[RANGEFINDER_MAX_INSTANCES];
The object pointed to by this pointer array is obtained through new operation, why not release it in the destructor function？
Also, I have checked many places and found that this is the case. Is there any mechanism that I overlooked？
Thank you very much!

**Comment by rmackay9** [comment]
Hi @xianglunkai,

No, there's no need to delete objects because the destructor should never be called.  As a general use in AP we try not to create any new objects in flight due to the risk of the new failing and leading to memory corruption or attempts to access uninitialised memory.  This is why you'll see that most objects are created soon after startup in one of the many init() methods.

**Comment by xianglunkai** [comment]
@rmackay9 
Thank you very much!
