### ISSUE TITLE
Rover: QuickTune velocity tune gains too high

### ISSUE THREAD

**Issue by xianglunkai** [ArduPilot/ardupilot#24729]
I found that PSC_ The parameters set by VEL are too large, resulting in oscillation behavior after turning at large angles. 
My personal opinion is:

1. Set P first instead of D, and D should be relatively small to prevent noise diffusion;

2. I can be set to 0 or 10% of the P value;

3. The maximum setting of D value should be 20% of P value;
4.
<img width="421" alt="图片2" src="https://github.com/ArduPilot/ardupilot/assets/48796694/bf765cc8-a385-4327-a8d1-c380e5d87136">

<img width="299" alt="图片1" src="https://github.com/ArduPilot/ardupilot/assets/48796694/9d4b5aea-1c25-430c-8a90-a44735ed997f">

**Comment by rmackay9** [comment]
Thanks for this.  I have a few ideas:

1. remove the velocity tune because it doesn't work well enough
2. the Slew Rate calculator can only detect relatively high frequency oscillations (3hz or higher).  Rover/Boat oscillations may be lower frequency than this meaning that we need to increase the SlewLimiter.cpp's WINDOW_MS definition to 1000 (or higher).  In my simulator tests however this did not help
3. try a different approach to find a good tune.  For example we could set the I gain to zero, then increase P until the root-mean-square error reduces.. perhaps then we could continue increasing it until it starts to deteriorate.

**Comment by xianglunkai** [comment]
@rmackay9 
I agree with your suggestion 1. In fact, manual adjustment of PSC is not difficult and the effect is acceptable. 
Also, why do we always start setting from D instead of P?

**Comment by rmackay9** [comment]
@xianglunkai,

Cool, I'll go ahead and remove it then (or you can of course).

I think we do D before P because tuning P may lead to us needing to reduce D.

**Comment by rmackay9** [comment]
I've created a PR here to greatly simplify the rover quick tune https://github.com/ArduPilot/ardupilot/pull/25629

**Comment by rmackay9** [comment]
We've removed the velocity tuning from the quick tune process so I'll close this issue.
