### ISSUE TITLE
Copter-4.0.7 clone with submodules issue

### ISSUE THREAD

**Issue by ItamarBiron** [ArduPilot/ardupilot#25414]
## Bug report

**Issue details**

I couldn't clone specific branch with submodules using the command 
` git clone --recursive https://github.com/ArduPilot/ardupilot.git --branch Copter-4.0.7`

**Version**
 Copter-4.0.7

**Platform**
[  ] Copter

**Logs**
stuck on :
Submodule 'modules/ChibiOS' (git://github.com/ArduPilot/ChibiOS.git) registered for path 'modules/ChibiOS'
Submodule 'modules/gbenchmark' (git://github.com/google/benchmark.git) registered for path 'modules/gbenchmark'
Submodule 'gtest' (git://github.com/ArduPilot/googletest) registered for path 'modules/gtest'
Submodule 'modules/libcanard' (git://github.com/ArduPilot/libcanard.git) registered for path 'modules/libcanard'
Submodule 'modules/mavlink' (git://github.com/ArduPilot/mavlink) registered for path 'modules/mavlink'
Submodule 'modules/uavcan' (git://github.com/ArduPilot/uavcan.git) registered for path 'modules/uavcan'
Submodule 'modules/waf' (git://github.com/ArduPilot/waf.git) registered for path 'modules/waf'
Cloning into '/home/itamarb/proj/personalProjects/assaf-help/ardupilot/ardupilot/modules/ChibiOS'...

**Comment by IamPete1** [comment]
You need this commit that fixes to https access for submodules. https://github.com/ArduPilot/ardupilot/commit/c127919bdd83e22d7a1b6ef041695d12c8bc9415

If you checkout the [Copter-4.0](https://github.com/ArduPilot/ardupilot/commits/Copter-4.0) branch rather than the 4.0.7 tag it is already included. 

GitHub decided to EOL the the `git:` method, not all our old branches and tags have the fix for that. 

Unless you have a very good reason you should not be using 4.0 in anycase, 4.4 is the current stable release.
