### ISSUE TITLE
Copter-4.5.0-beta2: Neopixel LEDs display incorrect colours

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#26295]
If multiple neopixel LEDs are connected they may show different colours from each other in 4.5.0 while in 4.4.4 they all show the same colour.

Below is a video using a CubeOrange with 3 neopixels connected.
https://github.com/ArduPilot/ardupilot/assets/1498098/f0a9a517-1dc4-4099-85e6-80ee0af6d7d2

The Neopixels are connected to CubeOrangePlus's AUX OUT 1, powered from a 5V BEC

Related [discussion is here](https://discuss.ardupilot.org/t/multiple-neopixels-dont-flash-in-sync/113620).

**Comment by andyp1per** [comment]
@rmackay9 if you are using CubeOrange then you really need to use a pull-up on the output. I have had this discussion on and off with @bugobliterator. Not saying this is the issue, but CubeOrange is definitely special electrically.

**Comment by bugobliterator** [comment]
https://discuss.cubepilot.org/t/rgb-neopixel-led-wiring-and-configuration/12129/8?u=sidbh Reference to the discussion where I answered this query.

![image](https://github.com/ArduPilot/ardupilot/assets/5697288/b5c20949-6efd-47cb-9192-63b7f92bc914)

The reason that NeoPixel LEDs don’t function on Cube is because they require > 0.7*Vcc signal line, Aux pins put out 3.3V and generally power tends to be solid 5V.
0.7*5 = 3.5V Reference 

If Neopixel are working without any modification, it is actually more of a cause of concern, as that indicates your 5V are not actually 5V but something like 4.7V, and possible symptom of this is brown-out on other hardware that require solid 5V for instance ESC or Autopilot power system etc...

**Comment by tridge** [comment]
I think it is more likely a slight change in clocking. I got the same symptoms (very similar flashing) on a G4 periph, and fixed it by overriding STM32_PPRE1 so we got a different peripheral clock on the timer

**Comment by andyp1per** [comment]
Fixed by https://github.com/ArduPilot/ardupilot/pull/26899
