### ISSUE TITLE
Possible bug with `force` argument in `AP_ParamT::set_and_save` function

### ISSUE THREAD

**Issue by postelzhuk** [ArduPilot/ardupilot#27132]
https://github.com/ArduPilot/ardupilot/blob/0c6f3964382a77ee375623cca029df7d4cd966fd/libraries/AP_Param/AP_ParamT.cpp#L70

```// Combined set and save
template<typename T, ap_var_type PT>
void AP_ParamT<T, PT>::set_and_save(const T &v) {
    bool force = fabsf((float)(_value - v)) < FLT_EPSILON;
    set(v);
    save(force);
}
```

`bool force` will be `true` when new value the same as current `_value`

**Comment by IamPete1** [comment]
The check for the not equal case is done here:
https://github.com/ArduPilot/ardupilot/blob/17083b54f8f882549576345e20a4b535e7823a60/libraries/AP_Param/AP_Param.cpp#L1207

That is to say, if there not equal you don't need to force save because it will be saved automatically. Having said that I'm not sure what it bothers to check, it could just always force in this case.

**Comment by postelzhuk** [comment]
Just need to clarify. 
1. Even if values are the same we force to write this values to the _eeprom_
2. `set_and_save_by_name` is a function that binded to the lua `param:set_and_save()`
3. In `AP_Param::save` there is an additional for equal case only for last parameter. 
4. In that case, calling several `param:set_and_save()` with the same values will always cause a heavy write operation. 

Is that all correct?

**Comment by IamPete1** [comment]
Yeah, that all sounds correct. We could add a binding for just `save` so you could do high rate `set` and then call save later.
