### ISSUE TITLE
Read and Send Data Throught UART, without using MAVLINK

### ISSUE THREAD

**Issue by peakyquest** [ArduPilot/ardupilot#27255]
**Platform**
[  ] All
[  ] AntennaTracker
[ X ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

Is there other way to read and send the data from pixhawk to companion computer without using mavlink. I want to send and and receive data only from uart? Is it possible? If not how to make a custom firmware and then upload it on pixhawk?

**Comment by khancyr** [comment]
You need to implement your own protocol if you don't want to use mavlink, so that require to code it.

Please look on the wiki how build a firmware. Depending what you want to send as data, just using LUA scripting would be enough. 

I will close this as this isn't an issue but user support, please ask user support questions on : https://discuss.ardupilot.org/
