### ISSUE TITLE
Four wheels steering rover

### ISSUE THREAD

**Issue by robodyne-robotics** [ArduPilot/ardupilot#28154]
Has there been any improvement in the implementation of the four wheels steering for a rover? It would be interesting to have the possibility to steer all the four wheels by keeping the same accuracy obtained for the skid-steering rover.

**Comment by rmackay9** [comment]
Hi @robodyne-robotics,

I guess you're looking for something like the mars rover? https://github.com/ArduPilot/ardupilot/issues/20563

There are some links there which is the latest I know about.

I'll go ahead and close this because our issues list is normally for enhancements requests and known bug (not questions).  Thanks for using AP!
