### ISSUE TITLE
copter-4.0.7 WPNAV advance_wp_target_along_track

### ISSUE THREAD

**Issue by UAVcihang** [ArduPilot/ardupilot#28902]
I recently looked at the previous code and found a bit of confusion in one area. Could you please explain the reason? Thank you.   

if (_track_length_xy >= WPNAV_YAW_DIST_MIN)
    {
        if (_pos_control.get_leash_xy() < WPNAV_YAW_DIST_MIN)
        {
            // if the leash is short (i.e. moving slowly) and destination is at least 2m horizontally, point along the segment from origin to destination
            set_yaw_cd(get_bearing_cd(_origin, _destination));
        } else
        {
            Vector3f horiz_leash_xy = final_target - curr_pos;
            horiz_leash_xy.z = 0;
            if (horiz_leash_xy.length() > MIN(WPNAV_YAW_DIST_MIN, _pos_control.get_leash_xy()*WPNAV_YAW_LEASH_PCT_MIN))
            {
                set_yaw_cd(RadiansToCentiDegrees(atan2f(horiz_leash_xy.y,horiz_leash_xy.x)));
            }
        }
    }

....................
why?
            if (horiz_leash_xy.length() > MIN(WPNAV_YAW_DIST_MIN, _pos_control.get_leash_xy()*WPNAV_YAW_LEASH_PCT_MIN))
            {
                set_yaw_cd(RadiansToCentiDegrees(atan2f(horiz_leash_xy.y,horiz_leash_xy.x)));
            }

**Comment by rmackay9** [comment]
Hi @UAVcihang,

This logic means that the vehicle only turns towards the next waypoint if the vehicle is moving at some percentage of the leash length.  E.g. not stopped.

4.0.7 is quite old now.  Sorry but when I see this I can't help but suggest that it's time to upgrade.

In any case, I'll go ahead and close this because it's really a question, not an issue
