### ISSUE TITLE
waf: create a wiki page

### ISSUE THREAD

**Issue by guludo** [ArduPilot/ardupilot#3840]
Hi all,

This is a followup of https://github.com/ArduPilot/ardupilot/issues/3823 .

Best,
Gustavo Sousa

**Comment by Naterater** [comment]
Done: http://ardupilot.org/dev/docs/building-setup-windows10.html#build-with-waf

**Comment by auturgy** [comment]
we don’t have a waf user guide external to BUILD.md which is a bit out of date: add to that the fact that the command to build a specific target is dynamic (ie with the hwdef system, the build script looks for the name of the board you want to configure and build, rather than having a list of build targets in the script), and it leads to confusion for newcomers imho.

Regards,

James

**Comment by rmackay9** [comment]
Is BUILD.mp out of date?  Tridge updated it in mid Nov.. i'm not aware of any issues with it.  I'm not sure how the build instructions ended up in BUILD.md rather than on the wiki but in any case, one place is better than two so let's not duplicate it... although you may not have been suggesting that in any case..

**Comment by IamPete1** [comment]
BUILD.md looks quite good to me, so I'm going to close, of course we can always improve documentation, but that should be tracked in a issue over on the wiki repo.
