### ISSUE TITLE
TradHeli: Throw mode

### ISSUE THREAD

**Issue by lvale** [ArduPilot/ardupilot#3939]
I was testing master for TradHeli and noticed that Throw mode appears for TradHeli. Might not be such a good idea to have this mode available for TradHeli.

**Comment by rmackay9** [comment]
I don't think it'll actually work for TradHeli.  So you may be able to select it from the list of available flight modes but it won't be possible to actually use it.
We don't allow the parameter descriptions to be different between tradheli and multicopters which is why it appears in the drop-down list of flight modes.
