### ISSUE TITLE
Tricopter V3.4-rc1: uncommanded yaw when flying backwards

### ISSUE THREAD

**Issue by GrahamDyer** [ArduPilot/ardupilot#4298]
#### Issue details

When flying backwards my aircraft exhibits an uncommanded yaw behavior. This was not apparent in v3.3.

![yawprob](https://cloud.githubusercontent.com/assets/3287001/15926088/558d87d6-2e3a-11e6-8ea2-ac9cfd5ffcc8.gif)
.
#### Version

AC V3.4-rc1
#### Platform

[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
#### Airframe type

Tricopter
#### Hardware type

AUAV-X2
#### Logs

https://www.dropbox.com/s/6ormmj1elpjdne5/95%2008-Jun-16%2016-42-56.bin?dl=0

**Comment by R-Lefebvre** [comment]
I can't download your logs form Dropbox to check.  This could be a yaw "blowout".  Basically if the yaw control is not capable of controlling the yaw due to backward flight, it blows around.  Very common on helicopters.  Not surprised to see a tricopter do it too.

Can you plot ATT.YawDes vs. ATT.Yaw?

**Comment by GrahamDyer** [comment]
Hi Rob, try this link: http://filebin.ca/2kJ1J4LGer7U/9508-Jun-1616-42-56.bin

Here is ATT.YawDes vs. ATT.Yaw

![yawprob2](https://cloud.githubusercontent.com/assets/3287001/15985716/4aeac1fe-2ff7-11e6-98a0-d5fb2a08c7fb.gif)

**Comment by rmackay9** [comment]
Really we should move this discussion to the discourse servers.  http://discuss.ardupilot.org/c/arducopter/copter34

Perhaps as Rob says, it looks like the target yaw is being dragged around by the actual yaw.  I think that means that the yaw control of the vehicle (whether because of tuning or because of some physical issue) is not capable of maintaining the yaw.

**Comment by OXINARF** [comment]
@GrahamDyer Have you tested this with the 3.4.1 stable release? Is the issue still present?

**Comment by OXINARF** [comment]
No answer for one month and a half, closing.

**Comment by GrahamDyer** [comment]
Sorry, I had replied but not in the issue: http://discuss.ardupilot.org/t/ac3-4-rc1-tricopter-test-flight-a-couple-problems-noted/9405/8

"I can confirm that the uncommanded yaw is no longer present. The tricopter maintains it's heading while flying backwards."

**Comment by OXINARF** [comment]
No problem, great to hear it's working. Thanks for testing!
