### ISSUE TITLE
Air restart 3.6.0 plane brownout

### ISSUE THREAD

**Issue by raptortrias** [ArduPilot/ardupilot#4426]
#### Issue details
Plane ,Autopilot stopped recording midflight, plane stopped responding after that

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover

#### Airframe type
Flying wing

#### Hardware type
Pixhawk
[24 05-07-2016 08-05-18.zip](https://github.com/ArduPilot/ardupilot/files/347291/24.05-07-2016.08-05-18.zip)

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by magicrub** [comment]
This is a support question, not a bug report. Please post questions like this to [discuss.ardupilot.org](url). I see your voltage drops just before it shuts off, consistent with a brownout. The cause is probably related to the almost x10 current draw a few moments before that. During your auto-tune you were pitching and rolling a lot, I suspect the battery came loose or you had some other electrical hardware failure.
