### ISSUE TITLE
Copter-3.4: motor twitch when disarmed when using OneShot

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#4789]
reported by Luis including this video: https://www.youtube.com/watch?v=w5QLcQU7Xro

**Comment by lvale** [comment]
@rmackay9 @tridge 

ok. more testing, this time with logic analyser attached to each of the 4 ESC's

Debugging the Oneshot125 twitching.

Used Flight controllers and ESC's
	PixRacer - ArduPilot Copter 3.4RC4
	CC3D Atom - Betaflight 2.9.0
	BLHeli Suite 16.3.14.7.0.2 
	ESC used - Blueseries 12A for Multicopter Motors - BLHeli revision 14.7 (Atmel based)
	
Test procedure

	PixRacer
		MOT_PWM_TYPE=0
		MOT_PWM_MAX=2000
		MOT_PWM_MIN=1000
		
		ESC calibrated as per wiki
		
		No problems observed
		
	PixRacer
		MOT_PWM_TYPE=1
		MOT_PWM_MAX=2000
		MOT_PWM_MIN=1000
		
		ESC calibrated as per wiki
		
		No problems observed
	
	PixRacer
		MOT_PWM_TYPE=2
		MOT_PWM_MAX=2000
		MOT_PWM_MIN=1000
		
		ESC calibrated as per wiki
		
		Motors twitch after Safety switch pressed, but still nor armed
		
	CC3D Betaflight
	
		Setting Motors  - Normal (equivalent as MOT_PWM_TYPE=0)
		
		ESC calibrated
		No issues,
	
	CC3D Betaflight
	
		Setting Motors  - OneShot125 (equivalent as MOT_PWM_TYPE=2)
		
		ESC calibrated
		Motors twitch as with ArduPilot
		
	
	Bypass connection directly with BLHeli suite
	
		ESC calibration done between 1000 and 2000 on the app
		
		Motors twitch

I would say that there might be an issue with several ESC's (both Atmel and Silabs) and Oneshot125. 

I still have to perform a few more tests, to see if I can get a workaround.

<img width="434" alt="screen shot 2016-09-06 at 16 27 50" src="https://cloud.githubusercontent.com/assets/3130363/18284717/f414a222-7462-11e6-8675-18445debae27.png">
<img width="439" alt="screen shot 2016-09-06 at 16 27 35" src="https://cloud.githubusercontent.com/assets/3130363/18284723/f4508bfc-7462-11e6-962c-bcdfceebca41.png">
<img width="583" alt="screen shot 2016-09-06 at 16 36 24" src="https://cloud.githubusercontent.com/assets/3130363/18284724/f453bdea-7462-11e6-8536-0b767aa7b800.png">
<img width="1004" alt="screen shot 2016-09-06 at 16 34 31" src="https://cloud.githubusercontent.com/assets/3130363/18284722/f44fa098-7462-11e6-9bea-729088196d6b.png">
<img width="1018" alt="screen shot 2016-09-06 at 16 34 22" src="https://cloud.githubusercontent.com/assets/3130363/18284720/f4497f92-7462-11e6-8709-3c6a2c8729be.png">
<img width="780" alt="screen shot 2016-09-06 at 16 34 10" src="https://cloud.githubusercontent.com/assets/3130363/18284721/f44bb8fc-7462-11e6-9724-e7f3a4e45f6b.png">
<img width="1001" alt="screen shot 2016-09-06 at 17 10 33" src="https://cloud.githubusercontent.com/assets/3130363/18284718/f42d2d38-7462-11e6-9755-8b765ced5152.png">
<img width="1184" alt="screen shot 2016-09-06 at 17 10 45" src="https://cloud.githubusercontent.com/assets/3130363/18284719/f446948a-7462-11e6-9372-b24a538160a1.png">
<img width="1212" alt="screen shot 2016-09-06 at 17 11 15" src="https://cloud.githubusercontent.com/assets/3130363/18284725/f45f49c6-7462-11e6-94e8-4aaf9bb107d9.png">

[motor test.mov.zip](https://github.com/ArduPilot/ardupilot/files/457396/motor.test.mov.zip)
[Logic traces.zip](https://github.com/ArduPilot/ardupilot/files/457397/Logic.traces.zip)

**Comment by lvale** [comment]
Further tests

As suggested on ardupilot.org forum, did try with safety switch disabled, and redid the ESC cal with MOT_PWM_TYPE 0, 1 and 2, and results are the same. OK with 0,1 twitching with 2.

Did try redoing ESC cal with MOT_PWM_MAX and MIN to the BLHeli suite suggested default values 1148 and 1832.
Results slightly different: This time regular OneShot took a long time to initialize the ESC's, every time that the vehicle started and the safety switch was pressed. OneShot 125 still the same twitching...No problem with regular PWM

And another one. ESC cal with MOT_PWM_MAX and MIN to 0 to go back to sending the Throttle PWM values (my radio - Taranis 982/2002)
Results slightly different: This time regular OneShot took a long time to initialize the ESC's, every time that the vehicle started and the safety switch was pressed. OneShot 125 also took a long time to signal the ESC's ready (30+ seconds) and then still the same twitching... Same delay on initializing the ESC's with regular PWM but less delay 5/10 seconds.

Curious that not all the ESC's took the same time to be initialized, and it was a random pattern, sometimes ESC1 was the first others ESC 4 was the first, etc, etc...

So redid the initial config MOT_PWM_MIN/MAX 1000/2000 MOT_PWM_TYPE to regular Oneshot (1) redid the ESC calibration and getting everything ready to fly tomorrow with RC4... (I hope).

I'm going to ask the BLHeli people if this is expected behaviour... we'll see....

**Comment by lvale** [comment]
With all this testing I also made a sugestion for Tower :) https://github.com/DroidPlanner/Tower/issues/1802

**Comment by rmackay9** [comment]
Great, thanks very much for testing this.

So I think because the twitching is also found when using the CC3D Betaflight software, we can conclude that it's very likely to be either the hardware or the BLHeli software.

**Comment by lvale** [comment]
Not only on Betaflight, but also using the BLHeli native tool to calibrate ESC's

**Comment by lvale** [comment]
Question raised on BLHeli thread at RCG http://www.rcgroups.com/forums/showpost.php?p=35663199&postcount=9846

**Comment by lvale** [comment]
I'll try with those values via MP, but I've used the BLHeli suite app and withe the suggested values it was twitching... 

be back in a bit :)

**Comment by lvale** [comment]
ok, Yes it works like @tabascoz said.

The problem is that although the ESC's only change to OneShot125 mode when they boot and get initialized to the signaling they receive at boot time. So although we can change freely the PWM_OUT mode between 1,2,3 without rebooting the PixHawk, the ESC's were initialized at Normal mode.

So better testing must be: change settings to OneShot125 on ArduPilot and adjust the PWM_MIN to whatever value you need. then power off everything and power on. As we are sending OneShot 125 signal then the ESC's get initialized to that, and the twitching occurs no matter the value we send.

**Comment by lvale** [comment]
Following on this theme...

So I think I found a workaround this issue.

Set your MOT_PWM_TYPE to 2 (OneShot125)

Now the values below have to be found by trial and error

Set the MOT_PWM_MIN to 1100

Calibrate the ESC's

Don't worry motors still twitching..

Power down, and power up

Now go to MOT_PWM_MIN and set it to a value below what was used for calibration, say 1000

Motors stop twitching because they are receiving a signal below their calibrated minimum.

Now arm, and check if the motors spin normally. In my case with the values above they were twitching, because the value they were receiving was very close to the minimum they were calibrated, so I played around with the MOT_PWM_MIN value used to calibrate the ESC until I was satisfied...

ok, It's a bit twisted process, and I'm not sure I made myself clear.

**Comment by lokanaft** [comment]
It's not a oneshot problem.
My setup work good after press safety with px4.io firmware with oneshot125.
And ardupilot work good, if disable safety switch.

**Comment by lvale** [comment]
> >It's not a oneshot problem.
> My setup work good after press safety with px4.io firmware with oneshot125.
> And ardupilot work good, if disable safety switch.

Please tell us on which values the PWM_MIN was calibrated on the ESC (assuming the calibration was performed also using OneShot125, and which values are on the output of the Flight controller with either PX4 and ArduPilot before and after the safety switch is pressed, and also when the safety switch is disabled

My testing without any flight controller plugged in to the ESC - direct from a USB/Com interface and only using the BLHeli config tool the twitching was repeatable.

**Comment by lokanaft** [comment]
My esc config:

![125](https://cloud.githubusercontent.com/assets/13313217/18408526/e7d23166-773a-11e6-862f-5b5fa1fe2ec5.PNG)

I calibrate it as in MissionPlanner instruction

**Comment by lvale** [comment]
@lokanaft 
Thanks. On a first glance the main differences, that could be related to this, are only the BLHeli version (14.6 vs 14.7), the PWM Frequency/Damped which is the active motor braking (Damped light vs Low), the Motor Timing (Medium Low vs Low) and perhaps also the Motor Startup Power (0,5 x 1.0).

Except for the version of BLHeli, I'll test the other differences and report back

**Comment by rmackay9** [comment]
@lvale, it's ok to close this right?  Because I think we've determined that it's not an issue with ardupilot.
I'll close but we can re-open if I've got that wrong.
