### ISSUE TITLE
Copter 3.4 - Aux Channels inconsistent behavior with Safety Switch

### ISSUE THREAD

**Issue by lvale** [ArduPilot/ardupilot#4798]
#### Issue details

Aux channels don't work when safety switch is off.
After pressing safety switch the AUX channel becomes active 
Pressing safety switch again does not "switch off" AUX channels.

Inconsistent behavior
#### Version

3.4RC4
#### Platform

[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
#### Airframe type

Quad
#### Hardware type

PixHawk

**Comment by rmackay9** [comment]
As discussed, there are two issues perhaps:
1. a bug in which the safety switch isn't stopping the output to the auxiliary channels
2. we should change the default in copter so that for the regular pixhawk board, the auxiliary channels (normally used for gimbals, landing gear, etc) are enabled by default.

**Comment by netptl39** [comment]
Additionally on AUX channels the if RCx_FUNCTION=0 and 1 the RCx_ TRIM is disregarded so output PWM is 0 even after Switch is ON

**Comment by lvale** [comment]
To be tested with 3.4 release

**Comment by rmackay9** [comment]
I think this is fixed.  @lvale, no pressure but could you give it a try with AC3.4.2?

**Comment by OXINARF** [comment]
@lvale Is this still valid?

**Comment by lvale** [comment]
Issue solved with channel mask PR

Closing
