### ISSUE TITLE
AHRS_Orientation configurations do not follow Tait-Bryan conventions

### ISSUE THREAD

**Issue by Georacer** [ArduPilot/ardupilot#4939]
#### Issue details

Currently, the list of options provided for the `AHRS_Orientation` parameter do not follow the aerospace convention (Tait-Bryan) for Euler angles, according to which:
-180<yaw<=180
-90<pitch<=90
-90<roll<=90
It is also not clear to me if at least the YPR order is used, but I think this is the case, thankfully.

This results in confused users (e.g. http://discuss.ardupilot.org/t/ahrs-orientation-yaw-180-roll-90/11936/3) which are used to aerospace angles.

Perhaps a re-naming of the parameter options would clarify the use of AHRS_Orientation.
#### Version

Current
#### Platform

[X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
#### Airframe type

All
#### Hardware type

All
#### Logs

N/A

**Comment by gmorph** [comment]
We can just update the description of each parameter value if that's going to make it better.  I'm not entirely convinced its needed however.  I don't think most users are "used" to aerospace angles.  Perhaps we should also include what the aerospace angle equivalent is.  However I'd suggest if they are used to aerospace angles they can probably work it out for themselves.

**Comment by magicrub** [comment]
There's also only so much we can do for apm 2.5 users which is the case
with this linked discuss post. Documenting the params and such is pretty
much all that could and should be done.

On Oct 9, 2016 8:17 PM, "Grant Morphett" <notifications@github.com> wrote:

We can just update the description of each parameter value if that's going
to make it better. I'm not entirely convinced its needed however. I don't
think most users are "used" to aerospace angles. Perhaps we should also
include what the aerospace angle equivalent is. However I'd suggest if they
are used to aerospace angles they can probably work it out for themselves.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ArduPilot/ardupilot/issues/4939#issuecomment-252532346>,
or mute the thread

**Comment by gmorph** [comment]
The issue still affects non APM users i.e. current hardware.  AHRS_Orientation parameter is still exactly the same and its documentation is still exactly the same.

**Comment by tridge** [comment]
the reason we didn't use those conventions is it gives negative numbers, and you can't have a C define for "YAW-90" as the minus isn't allowed. YAW270 is pretty clear I think. I actually think it is clearer than "YAW-90" as the - could be interpreted as a hyphen on reading

**Comment by gmorph** [comment]
I agree that the simple ones like YAW270 etc are easy to understand.  It was the one cited in the example above:
Roll = 90 Because it's on it's right side facing forward.
Yaw = 180 Because the direction arrow is backwards
which mapped to "Roll270Pitch180"
that I really struggled to get my head around and thought that the aerospace angles might help.  
Note I wasn't thinking of changing any code - just having an extra description column and mapping the current list of settings to the aerospace angle equivalents.

**Comment by Naterater** [comment]
I think the conventions are clearly documented and this issue should be closed.

**Comment by slovak194** [comment]
> I think the conventions are clearly documented and this issue should be closed.

Hi, could you please clarify where it is documented?

**Comment by IamPete1** [comment]
I think the conclusion is that yes there not matching the correct ranges, there also not in radians, but were not planning to change them, so I'm going to close. Not nearly as big a issue as it once was since we can no auto orientate compasses. 

Documentation is here: 
https://ardupilot.org/copter/docs/common-mounting-the-flight-controller.html#alternative-orientations
