### ISSUE TITLE
strip bebop2 build after performing build

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#4968]
The bebop2 build produces a large binary that actually may not fit on the bebop2 unless we strip it first using this command:
arm-linux-gnueabihf-strip ArduCopter.elf -o arducopter

I think we should do this after each build.

**Comment by OXINARF** [comment]
That is done in the firmware server right? We shouldn't do that in the build system, at least as an automatic step, because it's useful for debugging. We can add an option though.

(And by the way, I'm going to change the MP to install the binary in the volatile part of Bebop, that way the binary can grow without any issue, as well as the Bebop firmware)

**Comment by lucasdemarchi** [comment]
I agree.
