### ISSUE TITLE
Accelerometer calibration not taking into account autopilot orientation

### ISSUE THREAD

**Issue by annesteenbeek** [ArduPilot/ardupilot#5016]
#### Issue details
When doing the accelerometer calibration steps they would keep failing even though I set the the board orientation to yaw45 (This is the way the pixhawk is mounted on my quad). Calibration would keep failing until I did all the steps with the board orientad in the desired way instead of the whole quad. 

#### Version
APM copter V3.3.3 .
Tested with QGroundcontrol  v2.9.7 and latest Mission Planner.

#### Platform
[  ] All
[  ] AntennaTracker
[x] Copter
[  ] Plane
[  ] Rover

#### Airframe type
DIY quadcopter

#### Hardware type
Pixhawk

#### Logs
Don't have them available, but I could provide them if necessary.

**Comment by gmorph** [comment]
Not sure what you mean "board oriented in the desired way instead of the whole quad" but this is more of a support request and should be raised in the Copter discussion forums here - http://discuss.ardupilot.org/c/arducopter
A picture of your quad and a dataflash log file will really help otherwise not much can be done other then guessing what the problem might be.
Thanks.
