### ISSUE TITLE
Copter-3.4: PPM sum (FlySky FS-i6s) not working on Pixracer?

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#5112]
Some Pixracer users are reporting that AC3.4 is not accepting PPM input, in particular with the FlySky FS-i6s transmitter/receiver.

Report here: http://discuss.ardupilot.org/t/copter-3-4-has-been-released/12484

**Comment by rustutzman** [comment]
I bought my Pixracer back in January. The only version info I see is Pixracer v1. Glad to help with anything I can.

**Comment by rmackay9** [comment]
Here's a discussion in the support forums: http://discuss.ardupilot.org/t/ppm-with-pixracer/12448/6

**Comment by OXINARF** [comment]
This has been fixed in master and backported to the Copter-3.4 branch. Copter 3.4.1 is on its way out.

**Comment by rmackay9** [comment]
This is fixed in master and is going out with AC3.4.1.

**Comment by brizey02** [comment]
Seems still broken on ez-uhf, pixracer and taranis

**Comment by gregd72002** [comment]
@brizey02 I think that some pixracer fundamentally do not support inverted ppm signal. I have had similar issues with mine and the only way was to use a simple inverter in order to normalize it. You might want to give it a try

https://cloud.githubusercontent.com/assets/16255054/16666545/6bce6128-4488-11e6-9844-7b29ce07776d.png
