### ISSUE TITLE
Copter: add ability to change WPNAV_SPEED_UP, WPNAV_SPEED_DN as part of a mission

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#513]

**Comment by juandiazb** [comment]
Hello, I am interested in this topic. For the project I am working on, I have a mission plan in which the drone flies in AUTO mode to a WP at a certain altitude. After a few seconds, it descends on the same latitude and longitude to a WP that is some meters below. This descent is done very very slow in order to perform precision measurements.
For that, we lowered the WPNAV_SPEED_DN and it worked great. The issue is that now, whenever the mission is complete and the drone enters the LAND or RTL part of the mission plan (or if RTL mode is entered manually or after failsafe), the drone still descends at that speed, which is ridiculously slow. Normally I have to take manual control (PosHold Mode) and land it myself.

I do know that there is a parameter LAND_SPEED which applies below 10m. This does would not solve my issue because the first meters it will still descend very slow and may take a good minute to reach that 10m altitude. 
Has any work been done in this topic? I also know that the horizontal speed can be changed during the mission.
