### ISSUE TITLE
Meaningless LED Colours

### ISSUE THREAD

**Issue by mboland** [ArduPilot/ardupilot#5181]
#### Issue details
The LED colours are no longer dependable and can give wrong messages.

LED can display green but change to blue if you select a GPS mode prior to arming (and EKF pre-arm checks fail).
BUT
Arm in a manual mode, while LED is green, and switch to a GPS mode (while in the same EKF fail state), copter stays in manual, but the LED stays green. (By now a user would be wondering whats going on.)
Land and disarm but do not change from GPS mode. 
LED stays green. (To a user this would seem to indicate GPS mode is good to go.)
Arm while still in GPS mode and takeoff, LED stays green but copter is really still in Stab.

So the colour of the LED is no longer an indicator of anything, except pre-arm status.
If this is intended then safety, and common sense,  would dictate that the LED be turned off after arming.

I see this as a real safety issue.

#### Version
AC 3.4.x

#### Platform
[  ] All
[  ] AntennaTracker
[ X] Copter
[  ] Plane
[  ] Rover

#### Airframe type
Octocopter

#### Hardware type
3DR Pixhawk

**Comment by OXINARF** [comment]
Mike,

We have gone through this in the forum and, although you are correct that the led behavior should be better (#4918, #5028) and that a notification should be sent to the GCS when a mode is rejected (#5101), in this one you are wrong. You say:

> copter stays in manual

But then your comments go on as if you were in a GPS mode:

>Land and disarm but do not change from GPS mode

You can't change from GPS mode because you aren't in a GPS mode, it was rejected.

> LED stays green. (To a user this would seem to indicate GPS mode is good to go.) Arm while still in GPS mode and takeoff

Again, led stays green because you aren't in a GPS mode and so you are arming in the manual mode you were in.

There are already issues opened for the led and notification situations so I'm going to close this one. PRs are also welcomed.
