### ISSUE TITLE
Copter: add hardware switch to landing detection

### ISSUE THREAD

**Issue by sgofferj** [ArduPilot/ardupilot#523]
It would be a great addon to be able to connect NO or NC momentary switches to some analog input to have a definitive touchdown detection.
Ideally, it would be possible to configure if closing or opening the circuit means touchdown and which method is used for landing detection: vertical speed, hardware switch or both.

**Comment by Vabe7** [comment]
Is there still the need the switch? Because I would love to start coding with drones and such a switch would be perfect for me, since my copter just yesterday often didn't recognize that it already landed and then tipped over... 
I looked a bit into the linked pull request from 2014 where I could follow easily and into the land_detector.cpp where I understand most of it. 
But as far as I can tell I could just include Triggered into  ` if (motor_at_lower_limit && accel_stationary && descent_rate_low && rangefinder_check)` (probably with or, not and...) in [https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/land_detector.cpp](url) line 75 if it should still check the other parameters  or  add an else if, which just performs `set_land_complete(true)` if the switch is Triggered, that would need discussion if it is okay to assume that the craft has landed immediately if the status of the switch changed...

**Comment by WickedShell** [comment]
@Vabe7 Most of the work for this has been done already in #7893. That adds the switches to the landing gear library, and lets planes do some work with it. Some extensions to use it in copter for land detection would be needed still though.

**Comment by TunaLobster** [comment]
I believe this is in now. Unless I misunderstand how AP_LandingGear was implemented in Copter.

**Comment by rmackay9** [comment]
Ah, I didn't realise that landing gear had this.  As WickedShell says though we don't use the switch in the copter landing detection code.

**Comment by rmackay9** [comment]
The above linked PR has been merged so landing gear's WoW switch is involved in the land detection code so I'll close this issue.  It is possible that the detection code needs changing based upon the results of user testing but the basics are in there at least.
