### ISSUE TITLE
Add support for Dshot ESC protocol

### ISSUE THREAD

**Issue by dk7xe** [ArduPilot/ardupilot#5300]
#### Issue details
Dshot is a new "digital" ESC communication protocol currently developed by flyduino (Felix Niessen) together with borisb (betaflight). BLheli and KISS ESC are supporting this new protocol already.
-> https://www.rcgroups.com/forums/showthread.php?t=2756129

Advantages (as described by Felix on rcgroups) compared to the most used analog signals like PWM as also oneshot125 or 42 are:
- no signal jitter.. if the FC sends 1375 the ESC will receive 1375
- high resolution (2048steps)
- no oscillator drift (nomore calibrateing ESC's)
- more robust against spikes
- safer as every singnal has a CRC (cyclic redundancy check)
- maybe later some goodies like having the ESC's beep with the buzzer signal or things like that.

Since arducopter aims to support smaller/racer frames as well i suggest to add support for Dshot.

#### Platform
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover

#### Airframe type
all

#### Hardware type
Pixhawk

**Comment by magicrub** [comment]
Would be so much nicer of they would just use CAN and get on with it..

**Comment by R-Lefebvre** [comment]
Ooh, don't go there. They laughed at me last time I suggested it. Too complicated and expensive.

**Comment by proficnc** [comment]
CAN .... I went there :)

**Comment by lthall** [comment]
This is an important step forward and we should make sure this is supported in the next release.

While CAN ESC's will be great. BL_Heli represents mainstream ESC state of the art. It is benefiting from many thousands of racing quads that need to push the control capability to it's limit. 

This is another fantastic step forward for mainstream ESC development and we should support them not only because it is beneficial to us but also because they are a fellow open source community that is doing great things.

**Comment by lvale** [comment]
Second @lthall words. 

While CAN has the "potential" to be all for all, the community moves forward with easier/cheaper and effective solutions.

**Comment by tridge** [comment]
I think we should try and support this. The critical component we need is "DMA to a pin". I'm also not sure if we have enough DMA channels available. We may have to have options to choose between some of the other uses of DMA (eg. UART RX and SPI) and this.
It is likely that this will be a fairly tricky feature to develop, but I also think it is very worthwhile. The same basic system level features are needed to support FW update of ESC by flight controller.

**Comment by magicrub** [comment]
are the GPIOs memory mapped? The PIC32 on using MIPS arch has that and it
is quite handy. You can have DMA stream any thing via any event timing or
source to any GPIO pin because they're all memory mapped.

**Comment by dk7xe** [comment]
@tridge will u include support for the telemetry feedback from the ESC as well? This will eliminate the need for e.g. a current sensor because data can be read from ESC (if they have one like the KISS24re ESC).

**Comment by auturgy** [comment]
@tridge if you're going to do this I can donate some dshot esc's.

**Comment by dk7xe** [comment]
I can donate KISS24RE ESC as well if needed.

**Comment by magicrub** [comment]
I think this work may be underway.

**Comment by iskymaster** [comment]
Can someone please explain me what CAN is?

**Comment by auturgy** [comment]
https://en.m.wikipedia.org/wiki/CAN_bus

Regards,

James

**Comment by iskymaster** [comment]
James, Thanks!

May be the reason people have not jumped on it is because of the royalty fees?

**"Bosch holds patents on the technology, and manufacturers of CAN-compatible microprocessors pay license fees to Bosch, which are normally passed on to the customer in the price of the chip. Manufacturers of products with custom ASICs or FPGAs containing CAN-compatible modules need to pay a fee for the CAN Protocol License."**

**Comment by cmanley** [comment]
Is there any news or progress on this? Just about every new ESC sold these days uses Dshot, so it would be a pity to not be able to use them and also not have to calibrate ESCs anymore.

**Comment by netptl39** [comment]
Hi All, 
Is there any news on this issue?
I can also see the advantages of CAN vs Dshot, but: CAN ESCs are 80-100USD/pc while  32bit DShot1200 capable ESCs are 25USD/pc tops. BLheli_32 is out for awhile now and have ESC telemetry too. 
I am not a racing at all, but I could sure use less jitter on the copters.

**Comment by Saxin** [comment]
I don't recall ardupilot motor update rate, but i assume its on the order of 1k or so...
this makes dshot control rate gains irrelevant, yet the telemetry side of things, erpm and current can give some edge if used properly.
esc calibration will be absolute - a bonus.

**Comment by xkam1x** [comment]
I initially wanted to post comment here but ended up in PX4 issue on Dshot. Original comment:
I have been reading several forums about ESC protocol and it seems that digital bi-directional communication is a way to go.

The options are then i2c, CAN, UART and Dshot.
with i2c we have 400kbit/s.
CAN 1Mbit/s.
UART 1Mbit/s (depends on hardware).
Dshot 600kbit/s,

Since CAN needs licensing, it is probably best to avoid; otherwise cost of ESC will be higher and its adaptation will be slow.
i2c maybe a possible solution but I fear data integrity as SCL and SDA need to be synced.
UART is probably best as it does not require licensing and generally found on all micro controllers.
Dshot uses DMA which maybe difficult to program.

Personally I would like to see UART based ESC's and this how it can be done:
Hardware:

Invert UART signals.
Connect TX and RX togather.
Use 2 data lines, one with default pull high and other with default pull low to get differential signals (requires extra hardware but better reliability).
Share the UART bus with all ESC's.
Data packets could be sent like:
Sync1,Sync2,Motor 1 MSB,Motor 1 LSB,Motor 2 MSB,Motor 2 LSB,Motor 3 MSB,Motor 3 LSB,Motor 4 MSB,Motor 4 LSB,Data Request,Checksum

If whole message checksum has more overhead then we could use 11 bits for throttle value and 5 bits for checksum giving us 2048 levels and still keeping within 2 bytes.

Data request could contain first 4 bits as ESC ID and last 4 bits for data request. This allows for 15 motors and 15 different data packet structs, assuming last byte 0x00 means response not requested and it could be used to perform load balancing.

As soon as one message is sent, one of the ESC would respond with data packet requested and FC would process before requesting another.

This type of system does require ESC ID's to be set before hand but it is a onetime requirement.
Also we could change the Sync1 and Sync2 to indicate that the packet is throttle values or config parameters.

What do you think?

**Comment by auturgy** [comment]
Update: WIP still, but not far away from flight testing 
https://github.com/tridge/ardupilot/tree/chibios-dshot-wip

**Comment by demondev** [comment]
Can I ask if telemetry feedback from the ESC is being implemented also ? I to would be very happy to get rid of the current sensor, and gain voltage, current, RPM, and ESC temperature feedback.

**Comment by tridge** [comment]
@demondev yes, I am going to implement the telemetry feedback.
Status so far is:

- dshot works (150, 300, 600 and 1200)
- all done with DMAR so uses minimal number of DMA channels
- all auto-configured using hwdef.dat for the board
- we've had several successful test flights
- I have successfully done pass-thru configuration of both BLHeli_32 and BLHeli_S ESCs using the USB port on an ArduPilot board, using the BLHeliSuite programs on windows
- I've successfully upgraded firmware on ESCs using ArduPilot passthrough

I will be looking for people to do testing over the next few days. Please join the https://gitter.im/ArduPilot/ChibiOS gitter channel to join in the fun.

I'd also like to support Kiss ESCs, but haven't bought one yet. Donations welcome :-)

**Comment by dk7xe** [comment]
@tridge i have send a contact request via skype a few minutes ago. Maybe i can help u on KISS ESC.

**Comment by tridge** [comment]
@dk7xe got it just now (for some reason skype on linux didn't show it, but skype on my windows box did)

**Comment by dk7xe** [comment]
@tridge 4 KISS32A ESC are ordered now. Hope they will arrive soon at your end. Thanx for your work!

**Comment by padvinder95** [comment]
Have mentioned something in gitter but should maybe add here too: I am really looking forward to using this in Plane, too, since I use Aikon AK32 BLHeli32 ESCs and would love to use telemetry (and d-shot is nice too). Is there anything I can do to help, such as send some of those ESCs for testing, test something here myself, etc.?

**Comment by massimiliano-mantione** [comment]
Is there any specific reason why Dshot is currently not supported on rovers?

I am starting a new project, it is a small autonomous ground vehicle for various speed competitions (line following, track races with other vehicles, maze solving...).

I am still at the "hardware selection" phase, and having fast and accurate wheel speed control (with RPM telemetry) would be really nice :-)
Is it such a crazy idea to use BLHeli32 ESCs to accurately drive wheels instead of propellers?
(maybe it is, but I'd like to know...)

**Comment by magicrub** [comment]
You will want to use an encoder for that

**Comment by cs8425** [comment]
@massimiliano-mantione 
I think that's possible, but not so accurate as you thought.

**Comment by rmackay9** [comment]
This is in master so closing.  hope that's OK.
I don't know why BLHeli and Dshot aren't supported on Rover but I suspect it's easy to add.

**Comment by massimiliano-mantione** [comment]
Thanks for the replies, I'll look into using an encoder!

**Comment by awright424** [comment]
any idea of when this  will be available on arm boars? specifically bbbmini/pocketpilot?
