### ISSUE TITLE
SRXL and Remote RX channels 9-14 output to Pixhawk Aux outputs 1-6 (Spektrum AR7700 serial receiver)

### ISSUE THREAD

**Issue by GTMonster** [ArduPilot/ardupilot#5358]
#### Issue details
DX18 Stealth Black edition DSMX - 18 channel controller
Spektrum AR7700 serial receiver (remote RX out port) > (SPKT/DSM port) Pixhawk

I can see the first 8 channels operating when doing calibration in Mission Planner, however after setting RC_Function to 1 (pass-through) can't get any output from the aux channels to servos on aux channels 9-14

Same tried with SRXL port on AR7700. Still not working

+V voltage for receiver taken from +5V source so no issues with power

Is using a Spektrum serial receiver, is SRXL or remote receiver protocol able to access channels 9-14 available via the aux outputs 1-6 on the Pixhawk? Will they be? Is there a timescale? 

Many thanks for all your amazing work!! 

#### Version
3.3.3

#### Platform
 Copter

#### Airframe type
X4

#### Hardware type
Pixhawk 2.4.6

**Comment by OXINARF** [comment]
That is a support question and those should be posted at the forum (http://discuss.ardupilot.org). Also, you are using an older Copter version and since this isn't a safety issue there will be no enhancements done to 3.3. Please upgrade to 3.4 and if something isn't working in that version post in the forum.
