### ISSUE TITLE
mpu9250 external compass not detected

### ISSUE THREAD

**Issue by thoyo** [ArduPilot/ardupilot#5496]
I have a 3DR PX4 board. Following the instructions from here:
http://ardupilot.org/copter/docs/common-installing-3dr-ublox-gps-compass-module.html

I am able to "see" the external compass and calibrate it correctly on Mission Planner.

Now I try to use the MPU-9250 IMU as the external compass. The IMU is mounted on the Grove 9DOF board (http://wiki.seeed.cc/Grove-IMU_9DOF_v2.0/), which provides an I2C interface.

Unfortunately, the MPU is not detected by the PX4. 

Firmware version I am using: APM:Copter V3.4.2 (6076bdfc)

Possible error sources:
-MPU 9250 not supported (although I can see it in ardupilot/blob/master/libraries/AP_InertialSensor/AP_InertialSensor_Invensense.cpp)
->Should I switch to PX4 firmware for my specific purpose (https://github.com/PX4/Firmware)?
-Vcc on PX4 I2C pin and on Grove 9DOF don't match
-Others?

Thanks a lot, any help will be appreciated

**Comment by khancyr** [comment]
the wiring isn't the same : see : http://ardupilot.org/copter/docs/common-pixhawk-overview.html#common-pixhawk-overview , so first you need to reorder the cable to match : GND on GND, SDA on SDA, etc.

After they should be some configuration to do to acces the external IMU like the address, but I don't know how to setup this

**Comment by thoyo** [comment]
thanks a lot for your reply, @khancyr. But I had already reordered the cables, and I am sure all the lines on one board are connected properly to the other board.

**Comment by OXINARF** [comment]
I'm not an expert in this subject but I'll try to provide some answers:

- we definitely support MPU9250
- we definitely support the compass inside the MPU9250
- I'm not sure that we support accessing the compass via an external MPU9250
- it looks like the board you are using have direct I2C access to the compass via the auxiliar I2C, are you connecting through these or the primary I2C connector?

**Comment by OXINARF** [comment]
By the way, these questions should typically be posted in the forum (http://discuss.ardupilot.org) as it isn't either a confirmed bug nor a feature request.

**Comment by thoyo** [comment]
Thanks for your response, @OXINARF. I have tried connecting to the primary and to the auxiliary I2C connectors on my board, the result being the same (no external compass detected). 

Following your suggestion I moved the topic to the forum:
http://discuss.ardupilot.org/t/mpu9250-external-compass-not-detected/13932

Should I close the topic here? Thanks in advance

**Comment by OXINARF** [comment]
Yes, let's follow up there. Let me just say that I missed you are using 3.4 - I would try master, in 3.4 the compass detection is buried in the PX4 Firmware layer, much harder to know what's wrong.

**Comment by davidbitton** [comment]
I have this issue and have located the problem; at least for the speedybeef4. The issue lies in `AP_Compass.cpp` and the fact that when `define HAL_COMPASS_DEFAULT HAL_COMPASS_NONE` is defined the hwdef.dat file, `void Compass::_detect_backends(void)` doesn't call a `probe_mpu9250`.

Start by looking at line [915](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Compass/AP_Compass.cpp#L). Execution is obstensibly skipped  because of the `HAL_COMPASS_NONE` define. Execution then skips down to line [962](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Compass/AP_Compass.cpp#L962) and since `_backend_count` is in fact 0, that's it. I'm not sure which direction you want to go on the fix. However I'm ready willing and able to do so.

Thanks.
-dave
