### ISSUE TITLE
Copter: advanced TX tuning like in the "QuadPlane" code

### ISSUE THREAD

**Issue by robustini** [ArduPilot/ardupilot#5789]
I love the tuning system that @tridge has implemented for "QuadPlane" (VTOL), more intuitive and with less chance of error for newbies, i hope @rmackay9  will consider this awesome implementation also for the Copter:

http://ardupilot.org/plane/docs/common-transmitter-tuning.html

**Comment by peterbarker** [comment]
This tree was the basis of a PR to get the same functionality in Copter IIRC: https://github.com/tridge/ardupilot/tree/pr-copter-tuning

It doesn't rebase cleanly.

**Comment by OXINARF** [comment]
The PR for this is open, but hasn't been merged yet: #4065. Actually Randy mentioned @robustini there, (but without tagging) asking for your opinion.

Sometimes we leave issues and PRs for the same subject open, but that normally happens when PRs are opened to fix an issue. Since this was already at PR stage I'm going to close it. @robustini let me know if you think this should stay open anyway.
