### ISSUE TITLE
 “Bad LiDAR Health” even if "RNGFND_LANDIND = 1"  in arduplane firmware 3.8.0

### ISSUE THREAD

**Issue by ranqingfa** [ArduPilot/ardupilot#6122]
“Bad LiDAR Health” even if "RNGFND_LANDING = 1"  in arduplane firmware 3.8.0

 And when landing rangefinder really didnt work!

3.8.0 rc4

 Plane

Fixed Wing

pixhawk

Logs
https://pan.baidu.com/s/1pKIQRY7

Also why I can not upload a ZIP file?
![1](https://cloud.githubusercontent.com/assets/8523389/25470231/db144248-2b53-11e7-97b1-14804c21c636.png)

**Comment by ranqingfa** [comment]
I am using Maxbotic-I2C rangefinder, and in firmware 3.8.0 the RNGFND_TYPE = 2 for a Maxbotic-I2C rangefinder.

**Comment by OXINARF** [comment]
This is a support question and those should be posted in the forum (http://discuss.ardupilot.org). I was going to let it stay because it had a log, but that link is goes to an invalid page.

Please post in the forum, together with the log - if you can't upload the log in the forum, then try to put in Dropbox or Google Drive or another hosting service and link it in your post.

**Comment by ranqingfa** [comment]
https://pan.baidu.com/s/1pKIQRY7
This is a baidu Drive.

**Comment by ranqingfa** [comment]
Google Drive. Thanks a lot.
https://drive.google.com/file/d/0B6nj4A2GqXmWdFc2NTVRVWk4SjA/view?usp=sharing
