### ISSUE TITLE
BAD LOGGING prearm fail when logging to file and mavlink

### ISSUE THREAD

**Issue by Pedals2Paddles** [ArduPilot/ardupilot#6397]
#### Issue details
When the `LOG_BACKEND_TYPE`=3 (file and mavlink), and `LOG_DISARMED`=1 (enabled), there is a "BAD LOGGING" prearm failure. However this seems to be a false error, because logging is working fine.

If you change the backend type to only to file or only to mavlink, there is no failure. Only when trying to do both. And only when disarmed.

This is not just on mine. Everyone running master with this configuration is having the problem for months. I've worked around it by disabling the logging prearm check. But that's not a good fix.

Suggestions on what may be causing this?

#### Version
3.5+

#### Platform
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover

#### Airframe type
N/A

#### Hardware type
Pixhawk 2.1 and IMX companion computer

**Comment by njoubert** [comment]
We see the same thing. @ebethon

**Comment by peterbarker** [comment]
The problem comes about because the mavlink backend is always "started", so the checks here: https://github.com/ardupilot/ardupilot/blob/master/ArduCopter/system.cpp#L498 mean we never call "start()", which means the file backend reports failure.  The arming checks call `start_logging` without making the same checks, so it *appears* to work - 'though I'm pretty sure you don't actually get a file log until you arm, contrary to the parameter!

I'm currently looking at cleaning all of this stuff up - but to do so in such a way that it could go into 3.5

**Comment by Pedals2Paddles** [comment]
Cool. Thanks for working on this Peter!

**Comment by peterbarker** [comment]
Well, there's now a PR for this issue.  Testing would be appreciated.
