### ISSUE TITLE
#define SCHED_TASK_CLASS(classname, classptr, func, _rate_hz, _max_time_micros)

### ISSUE THREAD

**Issue by cyberdstar** [ArduPilot/ardupilot#6403]
how can i undertand the name begin with a dot such as .function .name .rate_hz  .max_time_micros in  SCHED_TASK_CLASS, usally is not permit in c or c++
[  ] Copter

**Comment by OXINARF** [comment]
It's a C99 functionality - designated initializers. It should actually be removed as it isn't allowed in C++11, but compilers are able to parse it since it is in the same order as the struct.

This issues list is for feature requests and confirmed bugs. For development questions please post in the forum (http://discuss.ardupilot.org) or ask in Gitter chat (http://gitter.im/ArduPilot/ardupilot).

**Comment by cyberdstar** [comment]
thanks a lot
