### ISSUE TITLE
SimpleBGC32 MAVLink packet loss when starting a GCS with Pixhawk connected to SimpleBGC32 mount

### ISSUE THREAD

**Issue by Dynode** [ArduPilot/ardupilot#6596]
### Issue details
The Simple BGC32 board (v2.63 b0) is connected to Pixhawk on Telem1/2, setup is for MAVLink protocol and mount (mnt_type Storm32). For those of you who don't know SBGC; the SBGC32 board is connected with it's own USB cable, shown as a COM port on the PC, that's where the SBGC GUI program talks.

Issue: The Simple BGC GUI program (through it's own port) indicates MAVLink packets are lost when APM Planner, Qgroundcontrol or a dronekit program is connected to the Pixhawk (through a 2nd USB cable / COM). It also happens when connecting through MAVProxy.

Anyone got an idea of what's going on with the packet loss?

#### Version
3.4.6

#### Platform
Copter is all I use

#### Airframe type
Octa

#### Hardware type
Pixhawk 1

#### Logs
No logs, got a screenshot of what I see in SBGC GUI:
![image](https://user-images.githubusercontent.com/17575688/28205388-1aa73a8a-6882-11e7-972b-7274b95d8110.png) (the parse errors are irrelevant to this issue)

**Comment by OXINARF** [comment]
This issues list is for feature requests and confirmed bugs. For user support please post in the forum (http://discuss.ardupilot.org).

This looks unrelated to ArduPilot itself, seems like some interaction between GCS and SimpleBCG GUI - since the last one is closed source it is hard to look at the issue. Your best option is to ask for SimpleBCG help.
