### ISSUE TITLE
Copter: sonar error detection

### ISSUE THREAD

**Issue by fryefryefrye** [ArduPilot/ardupilot#686]
The copter will fly away if something wrong with your sonar. 
For example, disconnect cable. Jammed sound path way.

When something wrong with your sonar, keep report a distance like 50cm.
The copter will keep climb in Loiter/Alt mode, because it think it keep 50cm above ground.
At the same time, the baro alt is growing, but APM just ignore it because the sonar alt was trusted.
Sonar should be disabled when baro alt shows climb more than10m, but sonar alt keep still.

**Comment by OXINARF** [comment]
This is quite an old issue and much has changed since then. Most rangefinder drivers will timeout if they receive no data - unless I'm missing something that's not possible in analog since an input is always available. We also can't assume that just because the vehicle is going up and rangefinder keeps the same altitude that it is wrong, for sure there are cases where it isn't.

Copter has an aux switch option that you can setup to stop the use of the rangefinder, which can be used for these cases.

For these reasons, I'm closing this. Feel free to comment if you feel that current code still isn't good enough.

**Comment by rmackay9** [comment]
I have a plan to use the EKF's terrain estimate instead of directly using the sonar/lidar.  It will take some significant testing though (the development isn't that hard).

**Comment by OXINARF** [comment]
@rmackay9 Yes, I think that is a good way forward, but I believe the EKF needs to be have rangefinder improvements before we can rely on its terrain estimate.
