### ISSUE TITLE
[Copter] Old version Quadcopter shows unstable flight (on SITL)

### ISSUE THREAD

**Issue by nix7965** [ArduPilot/ardupilot#6960]
#### Issue details
Hi, I let SITL drone execute some mission. Although it is old version, it shows strange behavior (You can refer to log).
Briefly, this mission is to let a drone move to east while moving to 400m altitude.
Almost at the end of "mission 3", this drone started to show super unstable flight. Then, it crashed.
(This happens 3 times out of 5 trials)
You can easily figure out this problem by reading yaw, roll and pitch. 

The question is that 1) is that a fixed problem in the recent version? I test SITL with gazebo which may require some modification to port to the recent Ardupilot I believe. I am not sure how other people test. (I just received SITL setting from my friend) / 2) if so, could you let me know what patches applied (if possible)? 

The mission that I used is ..
0   1   0   16  0   0   0   0   40.413299560546875  -86.9406051635742188    184.839996337890625 1
1   0   3   22  0   0   0   0   40.413299600000002  -86.9406051999999931    5   1
2   0   3   178 1   2000.0    95.0   0   0                   0                       0   1
3   0   3   16  0   0   0   0   40.413299600000002  -86.9196051999999977    400.0   1
4   0   3   16  0   0   0   0   40.413299600000002  -86.9406051999999931    5   1

+ I also have the same problems with the following mission. But, crash rarely happened.
QGC WPL 110
0   1   0   16  0   0   0   0   40.413299560546875  -86.9406051635742188    184.839996337890625 1
1   0   3   22  0   0   0   0   40.413299600000002  -86.9406051999999931    5   1
2   0   3   178 1   2000.0    95.0   0   0                   0                       0   1
3   0   3   16  0   0   0   0   40.408299600000002  -86.9296051999999977    150  1
4   0   3   16  0   0   0   0   40.415299600000002  -86.9396051999999977    150  1
5   0   3   16  0   0   0   0   40.413299600000002  -86.9406051999999931    5   1

#### Version
3.3 

#### Platform
[  ] All
[  ] AntennaTracker
[O] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
QuadCopter

#### Hardware type
SITL

#### Logs
[Unstable.BIN.zip](https://github.com/ArduPilot/ardupilot/files/1308034/Unstable.BIN.zip)

**Comment by OXINARF** [comment]
This issues list is for feature requests and confirmed bugs. For development questions please post in the forum (http://discuss.ardupilot.org) or ask in Gitter chat (http://gitter.im/ArduPilot/ardupilot).

We have done two releases since the version you are using come out, which, in ArduPilot time frame, means you are using a pretty old version - it's almost impossible to say if any commit fixed any eventual bug you might have encountered, too much has changed.
We have limited resources so asking a team member to go so far back to see what the code did then is probably more than anyone wants is available to do. I recommend that you update to latest version and test again and if you still have problems post in the forum.
