### ISSUE TITLE
Copter: GCS failsafe option to trigger in Auto

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#705]

**Comment by R-Lefebvre** [comment]
This is fixed with this commit. 

https://github.com/R-Lefebvre/ardupilot/commit/8360b3de059837329492938a8eab9b8d2beb0c56 

Need commentary on if this will be satisfactory for cases where Guided mode is being used for a companion computer.  I think it might work, as if the companion computer communication is lost, it will also RTL.  The only problem there, is the master parameter is called "GCS_Failsafe", not "MAVlink Failsafe".  Randy, you know this companion computer functionality better.  Would this all be acceptable?

**Comment by rmackay9** [comment]
With this commit from Rob the vehicle will RTL if the vehicle is in Guided mode.
https://github.com/diydrones/ardupilot/commit/5f19a431040277cb697ee07c41bd9c13122718a6

It's not clear if we want to trigger if the vehicle is in other modes like Auto.

**Comment by rmackay9** [comment]
Pushed to AC3.4.

**Comment by R-Lefebvre** [comment]
Randy, is this still relevant?

I think it is, looks like you pushed it to 3.4 in May.  So, reading the comments, I think what is wanted here, is expansion of the FS_GCS_ENABLE parameter, such that it will trigger an RTL if GCS connection is lost in Auto mode as well?  Simple as that?

**Comment by rmackay9** [comment]
@R-Lefebvre, yes, what you describe is just what we need I think.

**Comment by rmackay9** [comment]
Pushed to AC3.5.  We still need this but we're out of time for AC3.4.

**Comment by OXINARF** [comment]
Will be fixed by #5107 (which is waiting on me doing MAVProxy improvements in SITL support).

**Comment by Pedals2Paddles** [comment]
Closed by https://github.com/ArduPilot/ardupilot/pull/12790
