### ISSUE TITLE
Error when calibrating if secondary compass disabled

### ISSUE THREAD

**Issue by fredrikfalkman** [ArduPilot/ardupilot#7058]
I have never (I think) been able to get both compasses calibrated, but with secondary compass disabled (COMPASS_USE2 = 0) things have worked smoothly until I upgraded to 3.8.1
Now if I disable the secondary compass I get "MAV_CMD(42424) command failed" and the calibration process halts.
Is this a known error? Suggestions? Thanks!

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

#### Hardware type
Navio2

**Comment by OXINARF** [comment]
@fredrikfalkman I would say this is a QGC issue, but let's see what Don has to say about it.

@DonLakeFlyer Why is QGC sending specific mag bits (https://github.com/mavlink/qgroundcontrol/blob/master/src/AutoPilotPlugins/APM/APMSensorsComponentController.cc#L264) instead of using the all value (0)? The reason why @fredrikfalkman is getting a failure is that QGC is asking to calibrate a compass that the user disabled, so ArduPilot purposely fail the command.

**Comment by DonLakeFlyer** [comment]
I can't quite remember but I think it had something to do with being able to get individual status back for each compass being calibrated. That way I can show progress for each compass. Let me run that code again to see. I think it used to be ok to send bits for compasses which were disabled. Looks like that changed?

**Comment by DonLakeFlyer** [comment]
Fixed: https://github.com/mavlink/qgroundcontrol/pull/5772

**Comment by fredrikfalkman** [comment]
Nice!

**Comment by OXINARF** [comment]
@DonLakeFlyer 

> I can't quite remember but I think it had something to do with being able to get individual status back for each compass being calibrated.

I'm pretty sure that works even when sending the *calibrate all* command.

> I think it used to be ok to send bits for compasses which were disabled. Looks like that changed?

There was a change but it was one year ago... If you haven't read it, then I recommend looking at https://github.com/ArduPilot/ardupilot/pull/5061 where this change (and others) were made - namely reports will always be sent until GCS acks it has received them (the board has to be restarted anyway).
I wasn't aware that QGC actually used the mask instead of the _calibrate all_ option or I would have notified you (I actually opposed the change, but lost 🙂).

Glad it's fixed now, thanks!
