### ISSUE TITLE
QuadPlane: in AUTO mode turn the plane towards the first waypoint after the transition MC->FW, not during

### ISSUE THREAD

**Issue by robustini** [ArduPilot/ardupilot#7075]
#### Issue details
During the transition from MC to FW in AUTO, if the first WP is not perfectly aligned with the VTOL nose
the QuadPlane performs the turn during the transition (see the purple track inside the red circle), this could create flight instability.
It would be desirable instead to perform the turn towards the first waypoint after the transition, when is completed, not during, when it's already flying in fixed wing mode.

![vtol_turn](https://user-images.githubusercontent.com/3864712/31584318-66821aba-b1ac-11e7-9265-da7e103c6fc1.png)

#### Version
Plane V3.8.2

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover
[  ] Submarine

**Comment by magicrub** [comment]
Wouldn't it make more sense to yaw while in VTOL mode towards the next waypoint? There would need to be an altitude or height check after liftoff because we don't want yawing a few cm off the ground!

**Comment by robustini** [comment]
Maybe I explained myself wrong.
I mean the correct procedure is this:

1) takeoff in Copter mode
2) when the takeoff height has been reached transition in Plane mode
3) when the transition in Plane mode are complete yawing to the first waypoint

**Comment by magicrub** [comment]
I'm wondering why you would want to start flying forward in the wrong direction at all? Why not yaw around into the correct heading while still gaining altitude but before the transiton.

**Comment by robustini** [comment]
Because we can not think that any VTOL user is scrupulous... ;-)
Also the first waypoint could have been scheduled automatically and not necessarily in the direction of takeoff (upwind).

**Comment by robustini** [comment]
A classic example is the normal Plane: during the automatic takeoff the Plane proceeds in the nose direction until it reaches the predetermined height, then performs in the case of turning to the first waypoint, not during the takeoff.

**Comment by magicrub** [comment]
because "into wind". Got it.

**Comment by nick2204** [comment]
I agree, more control of what happens during transition would be good, it is really important to get the transition done as quickly as possible. The issue i submitted ( #7062 ) is another example of what happens if transition is not allowed to finish before navigation commences.

So far my workaround is always using weather vanning in VTOL, and then always putting a waypoint upwind at a safe distance for transition. Worst case distance is generally no wind, seeing that is always heading to wind.

It could be possible to make a combined solution for these and the request i made ( #7072 )for an independent safe transition distance on RTL

**Comment by tridge** [comment]
I'd be happy to add this as an option, but not to always wait for the turn. The reason is that where I fly if the plane goes straight ahead it could fly out of bounds if it doesn't turn (eg. fly over the clubhouse, or over the pilot). Waiting till transition is completed would be very bad for my flying location.
I would be happy to add a parameter to control this though. For example, we could have a maximum bank angle during transition, and/or have a flag for whether multicopter yaw control is applied during transition.
Perhaps we need a set of flags? maybe Q_OPTIONS, and have a bitmask of flags of this type? Users could set the bit to allow/disallow turns during transition.

**Comment by robustini** [comment]
Hello @tridge , thanks for the answer.
You know how VTOL I'm flying, in some configurations where the copter section has not been adequately sized the flight can become critical during that transitions, so it would be preferable to keep the wings leveled until the end of the transition, that is until the wing profiles begin to work to support the flight.
Usually to avoid this behavior before takeoff on an automatic mission I physically put the VTOL bow already directed to the position of the first waypoint, but in the case of automatic planning not necessarily the ground station software can predict my takeoff direction, I would love that there was this option only for that reason.
The max bank angle could be a good solution, in this way you can set the maximum deviation, if set to 0, it must be leveled.
I don't think we can use a bitmaks with an existing "Q" parameter for this feature, I've checked all.

**Comment by tridge** [comment]
yes, if all we want is a roll limit, then we should have a Q_TRANS_ROLL_MAX parameter. That would allow it to yaw using the multirotor control, but keep wings level.
Any other suggestions for a name for the parameter? It is certainly very easy to add.

**Comment by robustini** [comment]
Q_TRANS_ROLL_MAX, why not? Perfect!

**Comment by tridge** [comment]
This is fixed in 3.8.3beta1 using the new Q_OPTIONS flags. If you set Q_OPTIONS to 1 then that enables the level transition code. The wings are held within LEVEL_ROLL_LIMIT degrees until the transition is complete.
I re-used the existing LEVEL_ROLL_LIMIT parameter rather than adding a new parameter
