### ISSUE TITLE
Rover: use wheel encoders in motor control loops

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#7385]
Rover 3.2 supports wheel encoders but they are only used for position estimation.  They are not used to improve the vehicle's turn-rate and speed controllers.

The AP_Winch library (used in Copter-3.6+ to lower packages) includes some of what we need.  In particular it uses the wheel encoder output and adds a PID controller to better control the speed at which the winch line is released or retracted.

**Comment by mikerob** [comment]
Is this an opportunity to also allow use of single-line encoders for wheel speed (rather than only quadrature)? 
I know you'd really need two quadrature encoders on a skid steer vehicle, but for conventional steering you only need one wheel signal with direction, and the others could be single line. That would let you encode all four wheels with the available inputs.
That, in turn, eventually opens up traction control (comparing driven to non-driven wheel speed) and anti-skid braking.


    On Monday, 11 December 2017, 10:45:21 am AEDT, Randy Mackay <notifications@github.com> wrote:  
 
 
Rover 3.2 supports wheel encoders but they are only used for position estimation. They are not used to improve the vehicle's turn-rate and speed controllers.

The AP_Winch library (used in Copter-3.6+ to lower packages) includes some of what we need. In particular it uses the wheel encoder output and adds a PID controller to better control the speed at which the winch line is released or retracted.

**Comment by rmackay9** [comment]
This has been included in Rover-3.5.  The WRC_ parameters can be used to set this up.  We should document this though.
