### ISSUE TITLE
PROPOSAL: make version releases for  APM HAL independently from top vehicles application

### ISSUE THREAD

**Issue by hiro2233** [ArduPilot/ardupilot#7865]
Make version releases for APM HAL independently from top vehicles application.

Well, i don't know if say a feature for APM, but i think this is a great thing making a desired version for APM HAL on each realeases vehicles. With this we can structure and focus where we are in the development. I think is time to do it. Ardupcopter 3.x works with APM library v1.x.x sound better and make sense i think.

**Comment by magicrub** [comment]
Issue details are blank. Please say something...

**Comment by hiro2233** [comment]
@magicrub 👍

**Comment by WickedShell** [comment]
I don't really get the issue. We don't release HAL builds, each vehicle's release is tagged across the HAL/features it needs. If we said AC 3.6 was based on HAL 1.0 isn't actually that interesting because nothing else will target that HAL anyways as it will have changed by the next vehicle release. Similarly none of the current features from the vehicle level would come close to compiling on the various older APM boards without massive changes and cutting anyways.

**Comment by magicrub** [comment]
This is not in the scope of this autopilot project. Closing.
