### ISSUE TITLE
[Copter] Uncontrolled climbing, potential risk of flyaway ?

### ISSUE THREAD

**Issue by tony-8** [ArduPilot/ardupilot#7974]
#### Issue details
_Please describe the problem, or desired feature_

A/After beeing in stabilize mode, my quadcopter climbed at 22m above ground, then when switching to land mode, it continue climbing around 10 m higher (z-absolute=32m) before starting to climb down linearly. Please check out my log.

B/- geofense disabled in failsafe.
- Maxbotix sonar not setup, used default pixhawk parameters, no extra tuning.

C/Possible relationship with: 
https://github.com/ArduPilot/ardupilot/issues/4697

#### Version
_What version was the issue encountered with_
3.5.5
#### Platform
[  ] All
[  ] AntennaTracker
[ X ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_
Hj-H4 reptile quadcopter

#### Hardware type
_What autopilot hardware was used? (, pixracer, PX4FMU etc)_
pixhawk

#### Logs
_Please provide a link to any relevant logs that show the issue_
https://drive.google.com/file/d/1M7Kfd5kDE1b1RmjELYRLyb1Q6TT5Fztk/view

**Comment by rmackay9** [comment]
This is not really the place for support issues, they really belong in the forum.  Sorry to be strict but otherwise the developer to-do list turns into another support forum.

In any case, the logs appear normal.  I think what you're seeing is just the expected amount of time that it takes for the vehicle to slow the vehicle from a very rapid climb that was started in Stabilize mode.  So the pilot got it climbing at about 8m/s vertically and then when the vehicle was switch to Land mode, the climb was brought back down under control and then the vehicle began to descend.  It then appears it lost attitude control but this looks like a motor failure or perhaps it hit something.

![desvsactualclimbrate](https://user-images.githubusercontent.com/1498098/37695433-939ff044-2d12-11e8-876f-02be4a1a4cba.png)

Judging from the massive swings in climb rate while in stabilize mode, I suspect this is a new pilot who needs some more practice controlling the throttle manually.  No disrespect intended of course, it could all be intentional.  Anyway, I don't immediately see any software issues.
