### ISSUE TITLE
Baro: store dev_id to catch changes in number or type of barometers connected to flight controller

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#8067]
The AC_Compass library catches changes in a vehicle's compass setup (i.e. compasses added or removed) by storing each compass's device id in a parameter at the time that the compass calibration is done.  Then when the user goes to arm, we check that the device ids stored in the eeprom match the device ids detected after startup.

We could do something similar for barometers which might be useful now that external barometers (using CAN?) are becoming available.  We would need to decide when to store the device ids to eeprom because, unlike compasses which are only calibrated once by the user, barometers are calibrated at startup.

**Comment by WickedShell** [comment]
I suspect we could accomplish the primary desire of this by introducing the same concept of expected ID as we have for compasses. It requires the user to have set them of course, but for most users adding an explicit step of "save my baro ID's" just makes the setup more complicated. (And we can't use the existing MAVLink message that starts the calibration because it isn't unreasonable to be sending this every flight, which would cause you to overwrite the old ones)

**Comment by rmackay9** [comment]
This would have helped a user in this discussion re Copter-4.0: https://discuss.ardupilot.org/t/external-baro-sensor-on-can/51390/3

The problem is just that users have difficulty figuring out which barometers are being used.

**Comment by rmackay9** [comment]
Here's another discussion (separate from the one above) where this would have helped a user: https://discuss.ardupilot.org/t/barometer-glitch-inducing-ekf-primary-change/51345/5

**Comment by rmackay9** [comment]
PR https://github.com/ArduPilot/ardupilot/pull/14847 has resolved this
