### ISSUE TITLE
Plane: support retractable landing gear

### ISSUE THREAD

**Issue by ausi1972** [ArduPilot/ardupilot#818]
It would be great to have a parameter added for altitude trigger of an analogue output.
Set for something like 5m then as the model goes over 5m the analogue port is triggered which connected to a relay can trigger retracts to lift up the landing gear. Then as the model goes below the parameter the trigger will go back lowering the landing gear.

Hope that makes sense.

**Comment by R-Lefebvre** [comment]
What is the desire for a digital/relay output?  Are people still using pneumatic retracts, and do they operate with an on/off control instead of PWM/Servo?

I'm just trying to determine need, as I'm making a library for this that can be used for Copter and Plane.  Copters retracts use PWM control almost exclusively.  I expect modern electric airplane retracts would be the same, except for maybe very large systems?

I'm just trying to avoid the complexity if there's no real need for relay output.

**Comment by squilter** [comment]
@R-Lefebvre Is this issue done?

**Comment by R-Lefebvre** [comment]
No. This library is usable by plane, but needs to be implemented by plane.

**Comment by tridge** [comment]
I've added this to the 3.9.0 milestone for plane

**Comment by Kimo-k-o** [comment]
Hi tridge,
Checking in, wondering if you've made any progress on implementing v3.9.0 landing gear. I'm building a unique craft with ArduPlane on the BeagleBone Blue, and that function is an outstandingly important one for my application. Unfortunately my own coding skills are not yet up to the task.

**Comment by pompecukor** [comment]
We are really hoping this is getting some love soon. We need it for automating bay door of out belly gimbal units. Right now it need to be added as a mission command after take off and before landing. Which is so prone to human error (forgetting to add the close command). 
Any basic AUX channel PWM value that triggers at an altitude (set in the parameters) would be so lovely.
This would be usefull for so many things:
Gears,
Gimbal to home/safe postition.
None speed based flaps
you name it....

For us, this:
https://youtu.be/8jmmYi5Nlpc

**Comment by andresiko** [comment]
@pompecukor is so right! I was looking for this feature and I was sure that it already existed... I think that it will be really useful for planes to have an auto low height trigger in order to action things like Landing gear, Bimbal, camera protections etc...

Something really simple (and maybe very easy to implement!) if height is lower than X then trigger Landing gear.
