### ISSUE TITLE
Pixhawk needs a muted mode.

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/ardupilot#819]
Working with Pixhawk equipped UAS is extremely annoying.
All the loud beeping, and then it gets a GPS fix (indoor), and - starts the most mocking beeps of all "GPS Glitch" 

A nice and clean solution would be to have an option to disable all the sounds when needed, and they would return on next boot.

**Comment by abvgeej** [comment]
I unplugged my buzzer, as it is useless in air, quite much useless and annoying on ground, and i am used to locate my drone by GPS instead of beeps.

Those startup sounds are horrible, sound like a phone ringtone, and do not let me easily power it up without bothering other people or attracting unwanted attention.

+1 for a mute button

**Comment by rmackay9** [comment]
A mute mode would also be useful in removing this support issue that comes up now and then in which the buzzer causes one of the IMUs to alias leading to a short-term rapid climb in altitude.
http://diydrones.com/forum/topics/upgrade-to-3-3-2-alt-hold-rising-full-trottle-up

**Comment by Kelly-Foster** [comment]
+1 for mute ability.  Similar to others, would prefer to develop at home without disturbing others.

Kelly

**Comment by davidbuzz** [comment]
the standard methodology used here is to apply a small removable hardware "patch" to the buzzer....more specifically a bit of sticky tape over the noise maker. :-)

**Comment by rmackay9** [comment]
a BUZZ_ENABLE parameter has been added to master

**Comment by mbr1989** [comment]
push
