### ISSUE TITLE
Could we use two baro as airpseed？

### ISSUE THREAD

**Issue by liang-tang** [ArduPilot/ardupilot#8291]
#### Issue details
_Please describe the problem, or desired feature_

#### Version
_What version was the issue encountered with_

#### Platform
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_

#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by rmackay9** [comment]
questions should really go into the forums so I will close this.  Sorry to be strict but otherwise the issues list (which is for bugs and enhancements) turns into a support forum.

I'm not sure if two barometers could be used as an airspeed sensor.  It seems reasonable but I suspect that two separate sensors might drift apart due to other differences such as heat.
