### ISSUE TITLE
Rover: DPTH messages stored at 10hz regardless of whether echosounder has updated

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#9057]
Rover supports echosounders (i.e. under water range finders) as shown on the [wiki here](http://ardupilot.org/rover/docs/common-echologger-ect400.html) including storing a DPTH message to the dataflash message which includes the depth and vehicle's current lat/lon.  The issue however is that these DPTH messages are stored at 10hz even if there has been no new data from the echosounder.  This means that if the data is used for producing a 3D map, we end up with little lines instead of points.

It would be best if we stored the DPTH messages as soon as possible after the range finder has taken a new reading

**Comment by rmackay9** [comment]
This has been resolved in master and will go out with Rover-3.5

**Comment by alexhenao24** [comment]
Hi, I'm trying to obtain DPTH messages from my pixhwak 4, but I don't see that messages when I open the saved file (in SD card) by tapping "Review a Log" on Mission Planner.
I had tried Mission Planner from 1.3.63 to 1.3.68 versions
and Ardurover V3.42
May you help me please?, 
-What version of Mission Planner does the work?
-What version of Ardurover firmware is the correct for that?
Thanks in advance.

**Comment by rmackay9** [comment]
@alexhenao24,

It's probably best to post in the [Rover forums](https://discuss.ardupilot.org/c/ardurover/rover-35).

In any case, it may be because the RNGFND_ORIENT parameter hasn't been set to 25.

**Comment by alexhenao24** [comment]
> 
> 
> @alexhenao24,
> 
> It's probably best to post in the [Rover forums](https://discuss.ardupilot.org/c/ardurover/rover-35).
> 
> In any case, it may be because the RNGFND_ORIENT parameter hasn't been set to 25.

Hi, excuse me for post this here again, but I want to finish this story a least here.
I had RNGFND_ORIENT = 25 and the other parameters exactly as described in http://ardupilot.org/copter/docs/common-echologger-ect400.html
But no DPTH message anyway.
I think that is because my echo sounder is not an Echologger ECT 400 but an Airmar SS510. Do you think so?.
finally, I saw the values from de echo sounder in: Status--> rangefinder1 as in the  image:
![respuesta_rangefinder1_foro](https://user-images.githubusercontent.com/52712159/61159806-e1c67080-a4c2-11e9-9257-13a3612edd93.png)
And I logged those values in RGFD Dist1 as in the image:

![RGFD_foro](https://user-images.githubusercontent.com/52712159/61159851-0cb0c480-a4c3-11e9-98a6-53dc45ef15ba.png)

Any comments are useful and appreciated.
Thanks and have a good day!.

**Comment by jeff567** [comment]
for DPTH messages to be logged, the FRAME_CLASS parameter must be set to 2 (boat).  I would check this first.

**Comment by alexhenao24** [comment]
Yes, I have this parameter as you say:
FRAME_CLASS = 2

**Comment by jeff567** [comment]
not sure then.  I would open a thread on the rover forums as Randy suggested... you'll get much more visibility.  post your param file there too.

**Comment by alexhenao24** [comment]
Ok, thank you.
