### ISSUE TITLE
Copter: CH6 Tuning Min/Max displayed to user should always match parameter range

### ISSUE THREAD

**Issue by HansJochenKelle** [ArduPilot/ardupilot#906]
Issue concerns CH6-Option wrong numeric calculation to WPNAV_SPEED

Mission Planner 1.2.95 build 1.1.5150.11972
APN3.1.1

Menu = "Config/tuning"
Submenu "Extended Tuning"
Go to channel 6  ("Ch6") options.

I select in dropdown menu "WP_Speed",
I enter for Min = 0 (MP says 0,00000),
I enter for Max = 1 (MP says 1,00000),

press "Write Parameters", 
set on my transmitter the knob 6 to middle (in my opinion representing "0,5" or a half)
press "Refresh Screen",

and find at Nav_WP  the first variable, "WPNAV_SPEED" saying "500,0" (representing 500cm/s of a half of thousand).

There must be a wrong parameter calculation: The copter creates a value of 1000 times the value of the ch5-option setting.

I will open this issue both at github/arducopter and at google.code/arducopter
(And, yes i searched for earlier topics but found none)
Hope i could help.

Greetings, Hans-Jochen

**Comment by rmackay9** [comment]
pushing to AC3.4.

**Comment by rmackay9** [comment]
There is a PR from Tridge that could resolve this but we're simply out of time for AC3.4.  Pushing to AC3.5.

**Comment by iskess** [comment]
Wow this really got me by surprise today. It's easy to confuse but easy to understand if the issue was simple m/s versus cm/s. However its even more confusing. I wanted a range of 8 to12 m/s. I have to enter .8 and  1.2 to properly get 800 and 1200 for WPNAV_SPEED.  I wonder why MP would use /1000 rather than /100. I don't know what fix is proposed above, but both the parameter and MP should be changed to m/s. At least I've now tested my 3DR X8's maximum speed at 45 deg pitch. It hit 20 m/s at 100% throttle. I very nerve wracking survey mission!
