### ISSUE TITLE
Copter: Set home on Arming vs in air without prior 3D lock

### ISSUE THREAD

**Issue by jason4short** [ArduPilot/ardupilot#910]
When flying before 3d Lock is achieved, it is possible to get 3D lock in the air. The GPS position is most likely not accurate enough to store and could be miles away from the actual position. 

If the user RTL's or enters failsafe the copter will fly away. 

The user should receive notification home is not set on the GCS and the craft should loiter instead of RTL if home is not set by arming. Any other reasonable alternative fallback  approaches are welcome in the comments. 

The goal here is to be defensive against user error and not blaming the user.
Jason

**Comment by R-Lefebvre** [comment]
Isn't this solved with the GPS HDOP Pre-Arm check?

It seems to me the only way this problem could occur now is if the pre-arm check is turned off?

One problem that we can't solve in the program is that, if they were to take off and fly without GPS lock, and then the lock comes in the air, even if the GPS position indication is perfect, there's a good chance that the Home location that gets set is not actually home, but... just wherever the Copter happens to be at that moment.  So it will still RTL to somewhere other than the real launch point.  In most cases, this will be fine, but not always.  The only robust solution, is to prevent flying before GPS lock is achieved.

Since this is a GPS aided flight system, and many of our users cannot fly without GPS assistance, it doesn't make sense to allow them to take off before they have achieved a good GPS lock?

**Comment by magicrub** [comment]
Since we know if the home is set or not would it be very hard to not set
the home if already in flight and then not allow any GPS related modes
while home is not set.

**Comment by rmackay9** [comment]
pushed to AC3.4.
AC3.3 has a few improvements which largely resolve this:
1. the EKF is responsible for determining when the location is good before home is set so it's less likely that it will be a long way off.
2. the GCS can set the home location so it could warn the user

What's missing is:
3. the autopilot will still return and land at whatever location was captured as home (during flight).  This should be changed so it doesn't land (unless it really must because of low battery).
4. the autopilot needs to send a message to the GCS when the origin is set so it knows it's a good time to ask the user to set home.

**Comment by Hands0n** [comment]
Randy,
In the case of 4. would/could the notification appear on the Telemetry so any FPV fliers get the warning message also?  I think this would be a good thing.

**Comment by furynick** [comment]
Recently encountered this problem in 3.3.3 (see #3782).
Here is my thought about this issue.

There's two situation to take into account, first the RTL behaviour, second the GPS flight modes.
1) The RTL should only be available if a correct home position was recorded, it could be at arming when hdop is safe or manually by GCS. In this case the home should only be recorder when in Loiter/Pos Hold and stick centered.
2) GPS flight modes should only be available when hdop is safe, if a lock is acquired after takeoff this didn't invalidate all GPS features.

I'm sorry to be unable to submit a patch, I haven't enough skill and time to do it.

**Comment by rmackay9** [comment]
Item 4 from above is now resolved, "4. the autopilot needs to send a message to the GCS when the origin is set so it knows it's a good time to ask the user to set home."
In [Copter-3.4's commands.cpp file](https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/commands.cpp#L108) you can see these two lines which send the home to the ground station.
> // send new home location to GCS
    GCS_MAVLINK::send_home_all(loc);

**Comment by Naterater** [comment]
The home point should only be set if the HDOP is better than a number (maybe 1.5?) HDOP is a good indicator of horizontal accuracy, unlike the first position reading.

**Comment by auturgy** [comment]
HDOP doesn’t mean as much as you might think, but as Randy states above this is now linked to the ekf setting an origin, and reported to the user.
