### ISSUE TITLE
I want to  have a auto drop bottle algorithm . who can help me to  realize it ?

### ISSUE THREAD

**Issue by yuanzhengming** [ArduPilot/ardupilot#9184]
I want to  have a auto drop bottle algorithm . who can help me to  realize it ?

**Comment by rmackay9** [comment]
We support [grippers](http://ardupilot.org/copter/docs/common-gripper-landingpage.html) (two types) which can be used for delivery or bottle drops so I think I will close this item.  I suspect this issue is a request for a more advanced vision based bottle drop algorithm but I'm going to close it until this is more clear.  It's already possible to implement this kind of advanced bottle drop (this was done for the outback challenge event) but for me personally, it's potentially a bit too close to a "dual use" feature that I wouldn't be comfortable implementing it myself.
