### ISSUE TITLE
region flash overflow at ArduPlane-3.9.0 on fresh clone from master

### ISSUE THREAD

**Issue by 6ramr** [ArduPilot/ardupilot#9387]
Yesterday I freshly cloned to master and plane3.9 branches to local. I checked them out at ArduPlane-3.9.0 and ArduPlane-stable.

At ArduPlane-3.9.0 I get a compiler error that states that region flash is overflown.

At ArduPlane-stable I get a compiler error that states that there is no rule to make target "NavioLED_I2C.h"

I use px4-toolchain on windows and compile with eclipse.

**Comment by WickedShell** [comment]
If you are using make based build builds it's a known issue where PX4-v2 builds will overflow. Please use waf if you are building for those targets, otherwise make builds should be fitting.

Do a clean build (`waf distclean` or `make px4-clean` depending on what you are using) to resolve the issue with the missing target.

I'm closing this as it's a support issue, but if you need more help with it, [gitter](https://gitter.im/ArduPilot/ardupilot) or [discuss](https://discuss.ardupilot.org) would be the best places to ask.
