### ISSUE TITLE
Copter: request to add a delay param to LAND mission command

### ISSUE THREAD

**Issue by chapman** [ArduPilot/ardupilot#939]
(Lodging on behalf of Maurice Barnes, from drones-discuss 30-03-2014)

It would be great if we could implement a delay parameter to the LAND mission command, to enable landing for a specified period of time before executing the following TAKEOFF command. This would enable automated delivery systems (which may be a requirement of upcoming UAV competitions like Sparkfun).

Randy's response and implementation tips:

Seems like a reasonable thing to do on a delivery mission.  It’s not super hard for someone familiar with this part of the code but I’ve already got too much on my plate for AC3.2.  If you want to stick it into the GitHub issues list I’ll see when I can get to it but it might be a while. 

In case someone else wants to implement this change, I think what’s required is:

- Modify AP_Mission’s mavlink_to_mission_cmd() and mission_cmd_to_mavlink() functions to set the Mission_Command structure’s p1 value to the delay (stored in param1 of the mavlink command).  This will mean the delay is saved/stored to eeprom and available to the main code.

- Modify the verify_land() function to look at the cmd.p1 value and don’t return true until after p1 seconds has passed.  This should be very similar to how the verify_nav_wp() function accomplishes this.

https://github.com/diydrones/ardupilot/blob/master/ArduCopter/commands_logic.pde#L452

https://github.com/diydrones/ardupilot/blob/master/ArduCopter/commands_logic.pde#L488

It’s also not in the MAVLink protocol so we might need to ask Lorenz to change the protocol but that’s no big deal.  https://pixhawk.ethz.ch/mavlink/

**Comment by rmackay9** [comment]
pushing to AC3.4.

**Comment by nitirohilla** [comment]
@rmackay9 I am intersted in working on this issue. I've also looked into the required changes. But I have a query. As  in  AP_Mission’s mavlink_to_mission_cmd() and mission_cmd_to_mavlink() functions, cmd.p1 is used for abort target altitude in plane (as specified in the comment of the function in AP_Mission.cpp). 

Can we use the same paramter (param1) to define LAND delay time in Copter ?

**Comment by rmackay9** [comment]
@nitirohilla, this issue came up in a slightly different context so i've linked it to the other issue (that issue also has a link to yet another issue).  I think instead of adding a delay into the LAND command, we should create  a new navigation command called something like MAV_CMD_NAV_DELAY.  That makes the task a little bigger but it'll be a better result as well.  Think you're up for that?  I can provide some advice.

**Comment by nitirohilla** [comment]
Yes, I am willing to take this issue. Kindly help me to resolve below queries and validate my understanding.

1) Should MAV_CMD_NAV_DELAY command accept the delay time only in UTC time format (only hours, mins and seconds should be provided) or only in seconds or both? For example,

   param 1 -> seconds
   param 2 -> hour (UTC)
   param 3 -> minutes (UTC)
   param 4 -> seconds (UTC)

2) As per the pull request https://github.com/ArduPilot/ardupilot/pull/3708, to get time of week in ms time_week_ms() is used. As per my understanding instead of this function a new function get_system_clock() (which will call clock_gettime() with clock id as CLOCK_REALTIME to ger the current time) should be used.

3) As per the pull request https://github.com/ArduPilot/ardupilot/pull/3708, get_ms_until_time_of_week() should be remaned as get_time_utc() and should be define in AP_Common.cpp.

4) Since we are creating a new mavlink command MAV_CMD_NAV_DELAY. Kindly suggest the MAV ID that should be used for this command.

**Comment by rmackay9** [comment]
@nitirohilla 
I think it should accept a delay in either seconds or with a UTC time.  So the parameters you've listed above looks good to me.
2. i'm not sure actually :-).  we should certainly somehow try and use a system clock instead of getting it from the GPS.  So I think what you're suggesting is correct.
3. yes, i think so.
4.For the MAV_CMD number I think 93 or 94 would work (just before MAV_CMD_NAV_LAST).

**Comment by rmackay9** [comment]
The NAV_DELAY command was added so closing this issue.
