### ISSUE TITLE
EKF2/3: allow external position estimates to be provided at >20hz

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/ardupilot#9623]
The EKF2 accepts external position estimates but these should not be sent in at more than 20hz.  The reason is (I think) the same reason that [wheel encoder information cannot be provided at > 20hz](https://github.com/ArduPilot/ardupilot/issues/9303).  The same fixes hopefully fixes both issues.

I think @chobitsfan has experience with this particular issue.  If you could confirm @chobitsfan that would be great.

**Comment by chobitsfan** [comment]
In my tests, I find it seems that copters become less stable when I send external nav data faster than ~40Hz.  
In the beginning, copters fly better when data rate increased from 1Hz to 10Hz. But copter seems become unstable if data rate further increase to 50Hz.  It seems strange because in https://github.com/ArduPilot/ardupilot/blob/1e56ad483796ea7d98e237d79710320a2652e618/libraries/AP_NavEKF2/AP_NavEKF2_Measurements.cpp#L826 , it already limit data rate to ~14Hz. I am re-config motion capture system now, I will do more test once I finish it.

**Comment by rmackay9** [comment]
EKF3 (and maybe EKF2) support external position and speed estimates at up to 50hz now.
