### ISSUE TITLE
Plane: improve BRD_SAFETY_ENABLE defaulting

### ISSUE THREAD

**Issue by GlidLov** [ArduPilot/ardupilot#9939]
### Bug report

SBUS Out port (next to "cons" port) is not working on any 3.6.x (i think it's an old issue, but can't test on older versions) on the Pixhawk 2.1 "cube".
The only way to get an SBus out is to use the serial ports, assigning one to work as Sbus out.
I tested with an oscilloscope and SBUS out port is never working, all channels are "0". I tried all the possible parameters (refresh rate, etc), no changes.

**Version**

3.6.x

**Platform**
[ X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Hardware type**

Pixhawk 2.1

**Comment by GlidLov** [comment]
update: 

it's not working if BRD_SAFETY_ENABLE = 0

**Comment by matthewgan** [comment]
Same problem.
It's not working in BRD_SAFETY_ENABLE = 1 and BRD_SBUS_OUT = 1 here.
on Pixhawk 2.1
FIXED WING

**Comment by matthewgan** [comment]
Found reason in the code:
in order to enable the sbus output, you must arm it to pass the if (status.io_enable())
so it is somehow not a bug, but designed that way.
Who designed it please explain why doing this?

**Comment by rmackay9** [comment]
@matthewgan, ok great that you got to the bottom of this.

I think the underlying issue is perhaps the defaulting of the BRD_SAFETY_MASK is not ideal on Plane.  This parameter controls which outputs are affected by the safety switch.  The screen shot below of the MP shows that if the user clicks on the parameter's Value from the Full Parameter Tree screen the individual outputs are affected by the safety switch (checked channels will move regardless of the state of the safety switch).

![brd-safety-mask](https://user-images.githubusercontent.com/1498098/56701063-69a8a400-6738-11e9-8b93-bc8207360647.png)

**Comment by rmackay9** [comment]
I've modified the subject line of this issue a bit, hope that's OK.

**Comment by IamPete1** [comment]
I'm going to close, the users original issue has been resolved and I don't think we would ever be brave enough to change the default safety behavior.
